// import {mockData} from './mockdata.js';

/* global db print */
/* eslint no-restricted-globals: "off" */


////https://www.generatedata.com/

const mockData =[
	{
		"name": "Dalton Riggs",
		"contactFrequency": "Weekly",
		"email": "sodales.purus@orciDonec.co.uk",
		"phone": "1-806-877-1949",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "Curae;",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Duis Ltd",
		"title": "molestie"
	},
	{
		"name": "Hayden X. Huffman",
		"contactFrequency": "Quarterly",
		"email": "adipiscing.elit@Namac.org",
		"phone": "1-988-160-4915",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "nonummy",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Aenean Eget Magna Institute",
		"title": "magna. Cras convallis"
	},
	{
		"name": "Harriet Blevins",
		"contactFrequency": "Weekly",
		"email": "orci@ornareFuscemollis.ca",
		"phone": "1-746-234-2189",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "erat",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Ullamcorper Duis Cursus LLC",
		"title": "mattis. Integer eu"
	},
	{
		"name": "Petra W. Chen",
		"contactFrequency": "None",
		"email": "Fusce.diam@ullamcorperDuiscursus.org",
		"phone": "1-933-477-4432",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "auctor",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Eget Ltd",
		"title": "libero dui"
	},
	{
		"name": "Marah Y. Flores",
		"contactFrequency": "Quarterly",
		"email": "nonummy@faucibusleo.net",
		"phone": "1-878-304-9754",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "vulputate",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Gravida Mauris Inc.",
		"title": "dolor dolor,"
	},
	{
		"name": "Justine Hull",
		"contactFrequency": "Yearly",
		"email": "Nullam.ut.nisi@etrutrum.org",
		"phone": "1-839-843-9154",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "scelerisque,",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Duis Cursus Associates",
		"title": "sem"
	},
	{
		"name": "Willa Acosta",
		"contactFrequency": "None",
		"email": "tincidunt.aliquam@consequat.ca",
		"phone": "1-408-643-6121",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "leo",
		"activeStatus": true,
		"notes": "Lorem",
		"company": "Tincidunt Company",
		"title": "torquent per conubia"
	},
	{
		"name": "Kimberley Y. Castro",
		"contactFrequency": "Quarterly",
		"email": "sem@nislNulla.net",
		"phone": "1-281-628-0171",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "sit",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Aenean Massa Corporation",
		"title": "tincidunt,"
	},
	{
		"name": "Carter Kane",
		"contactFrequency": "Quarterly",
		"email": "nunc@ac.edu",
		"phone": "1-911-969-9836",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "sollicitudin",
		"activeStatus": false,
		"notes": "Lorem",
		"company": "Felis Adipiscing Corporation",
		"title": "Fusce"
	},
	{
		"name": "Dean Heath",
		"contactFrequency": "BiWeekly",
		"email": "egestas.a.dui@gravidanuncsed.org",
		"phone": "1-572-410-2449",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "lectus.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Dolor Sit Ltd",
		"title": "auctor odio"
	},
	{
		"name": "Bertha M. Floyd",
		"contactFrequency": "Weekly",
		"email": "aliquet@nuncnulla.net",
		"phone": "1-287-182-6245",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "interdum",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Cum Sociis Natoque PC",
		"title": "accumsan laoreet ipsum."
	},
	{
		"name": "Isadora Cook",
		"contactFrequency": "Monthly",
		"email": "a.dui@mattis.org",
		"phone": "1-589-683-8270",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "non",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Sed Hendrerit A Inc.",
		"title": "varius ultrices,"
	},
	{
		"name": "Karyn Leonard",
		"contactFrequency": "Quarterly",
		"email": "dis.parturient.montes@metusfacilisislorem.org",
		"phone": "1-719-901-8779",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "sem.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Nonummy Ac LLP",
		"title": "tellus."
	},
	{
		"name": "Emerson O. Whitney",
		"contactFrequency": "Quarterly",
		"email": "arcu.imperdiet.ullamcorper@tinciduntDonecvitae.ca",
		"phone": "1-778-715-2852",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "Curabitur",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Vel Corp.",
		"title": "augue"
	},
	{
		"name": "Callie Hopper",
		"contactFrequency": "BiWeekly",
		"email": "lorem.Donec@elitafeugiat.org",
		"phone": "1-225-326-2529",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "vel",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Tellus Id Corp.",
		"title": "risus. In mi"
	},
	{
		"name": "Ann Douglas",
		"contactFrequency": "Yearly",
		"email": "urna.Ut.tincidunt@pharetraNamac.ca",
		"phone": "1-714-175-2093",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "nec",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Tempus Non Institute",
		"title": "Nulla"
	},
	{
		"name": "Teagan F. Smith",
		"contactFrequency": "Weekly",
		"email": "ipsum.Suspendisse.non@Aliquamerat.org",
		"phone": "1-889-371-9476",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "luctus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Lacus Institute",
		"title": "molestie orci"
	},
	{
		"name": "Ursula W. Mendoza",
		"contactFrequency": "Yearly",
		"email": "elit@acsemut.edu",
		"phone": "1-330-601-9220",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "luctus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "At Libero Morbi LLP",
		"title": "et malesuada fames"
	},
	{
		"name": "Aretha P. Berg",
		"contactFrequency": "Monthly",
		"email": "Praesent@egestasSed.ca",
		"phone": "1-346-713-2730",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "elementum,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Placerat Orci Lacus Inc.",
		"title": "blandit"
	},
	{
		"name": "Xanthus Fulton",
		"contactFrequency": "Yearly",
		"email": "id.enim@maurisblanditmattis.co.uk",
		"phone": "1-268-399-4219",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "Aliquam",
		"activeStatus": false,
		"notes": "Lorem",
		"company": "Blandit Viverra Limited",
		"title": "quis turpis"
	},
	{
		"name": "Ulla Morris",
		"contactFrequency": "None",
		"email": "sapien.molestie.orci@Donecfeugiat.ca",
		"phone": "1-740-553-4345",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "non",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Maecenas Malesuada Fringilla Incorporated",
		"title": "egestas blandit."
	},
	{
		"name": "Charde K. Benjamin",
		"contactFrequency": "Yearly",
		"email": "massa@ultrices.ca",
		"phone": "1-371-185-8058",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "Aenean",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Auctor Mauris Corp.",
		"title": "libero dui"
	},
	{
		"name": "Bryar L. Graham",
		"contactFrequency": "Yearly",
		"email": "et.magnis.dis@hendreritconsectetuercursus.co.uk",
		"phone": "1-984-533-7595",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "quis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit",
		"company": "Semper Ltd",
		"title": "erat"
	},
	{
		"name": "Noah Q. Downs",
		"contactFrequency": "Yearly",
		"email": "Fusce.aliquam.enim@inconsequatenim.ca",
		"phone": "1-350-864-3848",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "felis",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Quisque Tincidunt Pede Ltd",
		"title": "orci"
	},
	{
		"name": "Lunea Burke",
		"contactFrequency": "Quarterly",
		"email": "Proin.ultrices.Duis@nec.ca",
		"phone": "1-419-674-6354",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "In",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Arcu Company",
		"title": "non enim"
	},
	{
		"name": "Martena Mayer",
		"contactFrequency": "Monthly",
		"email": "gravida.sit.amet@dui.net",
		"phone": "1-658-889-0497",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "enim,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Tristique PC",
		"title": "Etiam ligula"
	},
	{
		"name": "Edward Lynn",
		"contactFrequency": "BiWeekly",
		"email": "Morbi@quis.edu",
		"phone": "1-521-666-5858",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "aliquet.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Et Company",
		"title": "molestie arcu. Sed"
	},
	{
		"name": "Damian Fowler",
		"contactFrequency": "Quarterly",
		"email": "eu.nulla@parturient.co.uk",
		"phone": "1-949-805-6426",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "tempus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor",
		"company": "Ante Dictum Cursus Inc.",
		"title": "mauris,"
	},
	{
		"name": "Frances Sears",
		"contactFrequency": "None",
		"email": "augue.Sed.molestie@sedturpis.co.uk",
		"phone": "1-187-861-7748",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "Donec",
		"activeStatus": true,
		"notes": "Lorem ipsum",
		"company": "Malesuada Foundation",
		"title": "sit amet"
	},
	{
		"name": "Mona X. Moran",
		"contactFrequency": "Quarterly",
		"email": "scelerisque@intempuseu.net",
		"phone": "1-459-878-1699",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "eu",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Nec Foundation",
		"title": "tempor bibendum."
	},
	{
		"name": "Nicole N. Robbins",
		"contactFrequency": "Biannual",
		"email": "litora.torquent@sagittisaugue.net",
		"phone": "1-810-753-3919",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "sem",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Et Risus Foundation",
		"title": "elit,"
	},
	{
		"name": "Zelda K. Wynn",
		"contactFrequency": "BiWeekly",
		"email": "primis.in@utodio.org",
		"phone": "1-987-152-4952",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "risus.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Eu Lacus Quisque Corporation",
		"title": "gravida molestie arcu."
	},
	{
		"name": "Colby Frye",
		"contactFrequency": "Yearly",
		"email": "habitant@non.net",
		"phone": "1-910-347-7889",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "luctus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Consequat Enim Associates",
		"title": "lacus."
	},
	{
		"name": "Phillip F. Donaldson",
		"contactFrequency": "Biannual",
		"email": "egestas.rhoncus@Crasdictumultricies.net",
		"phone": "1-113-910-1700",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "eget,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Risus Institute",
		"title": "massa non"
	},
	{
		"name": "Roth Thomas",
		"contactFrequency": "BiWeekly",
		"email": "Aliquam@et.org",
		"phone": "1-314-671-2828",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "consequat",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Vulputate Lacus Cras Industries",
		"title": "eros"
	},
	{
		"name": "Breanna T. Beck",
		"contactFrequency": "Biannual",
		"email": "risus.a.ultricies@odio.co.uk",
		"phone": "1-798-641-9860",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "Sed",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Est Tempor Bibendum PC",
		"title": "ornare,"
	},
	{
		"name": "Phelan G. Serrano",
		"contactFrequency": "Yearly",
		"email": "nisl.arcu@Integer.net",
		"phone": "1-744-336-3550",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "mauris",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Eget Foundation",
		"title": "erat. Vivamus"
	},
	{
		"name": "Finn Berger",
		"contactFrequency": "BiWeekly",
		"email": "Morbi.sit.amet@dolornonummyac.ca",
		"phone": "1-500-726-0750",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "mollis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Erat PC",
		"title": "sit amet"
	},
	{
		"name": "Chase Dorsey",
		"contactFrequency": "Weekly",
		"email": "malesuada.malesuada.Integer@molestiedapibusligula.org",
		"phone": "1-835-670-2735",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "imperdiet",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Nonummy Limited",
		"title": "volutpat nunc sit"
	},
	{
		"name": "Dakota W. Harris",
		"contactFrequency": "Quarterly",
		"email": "et.risus.Quisque@libero.co.uk",
		"phone": "1-762-128-8562",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "ac",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Dolor Incorporated",
		"title": "vitae"
	},
	{
		"name": "Dillon L. Workman",
		"contactFrequency": "Monthly",
		"email": "a@Sednec.com",
		"phone": "1-189-471-4456",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "arcu.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Malesuada Limited",
		"title": "fringilla, porttitor vulputate,"
	},
	{
		"name": "Thaddeus Sellers",
		"contactFrequency": "None",
		"email": "nec@pellentesqueeget.com",
		"phone": "1-210-195-9502",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "vehicula.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Suspendisse Aliquet Sem Inc.",
		"title": "Aliquam nisl."
	},
	{
		"name": "Naomi T. Ross",
		"contactFrequency": "Yearly",
		"email": "turpis.egestas@lacusvariuset.com",
		"phone": "1-259-809-3492",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "risus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Purus Limited",
		"title": "dapibus id,"
	},
	{
		"name": "John Garner",
		"contactFrequency": "Biannual",
		"email": "pretium.neque.Morbi@diam.ca",
		"phone": "1-840-525-3861",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "lacus.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Scelerisque Neque Nullam Corporation",
		"title": "molestie arcu. Sed"
	},
	{
		"name": "Nola U. Rose",
		"contactFrequency": "None",
		"email": "ornare@quis.org",
		"phone": "1-874-757-7782",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "nec,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit",
		"company": "Eu Company",
		"title": "pharetra nibh. Aliquam"
	},
	{
		"name": "Arsenio Adams",
		"contactFrequency": "Yearly",
		"email": "enim@commodo.com",
		"phone": "1-844-859-3284",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "porttitor",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Sagittis Institute",
		"title": "nostra, per inceptos"
	},
	{
		"name": "Vance Trevino",
		"contactFrequency": "None",
		"email": "ut@auctornonfeugiat.edu",
		"phone": "1-159-459-7703",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "sed",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Fermentum Corporation",
		"title": "turpis vitae"
	},
	{
		"name": "Shelley K. Frank",
		"contactFrequency": "Yearly",
		"email": "Suspendisse@Donecdignissimmagna.edu",
		"phone": "1-298-898-1241",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "eget,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Integer Sem Ltd",
		"title": "vitae, orci. Phasellus"
	},
	{
		"name": "Gwendolyn K. Harding",
		"contactFrequency": "Biannual",
		"email": "vitae.erat.vel@sedhendrerit.ca",
		"phone": "1-126-355-7255",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "Nulla",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit",
		"company": "Malesuada Foundation",
		"title": "porttitor scelerisque"
	},
	{
		"name": "Clio B. Fisher",
		"contactFrequency": "Yearly",
		"email": "quis@penatibuset.com",
		"phone": "1-224-470-6070",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "purus,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Eget Metus In Corp.",
		"title": "pharetra nibh."
	},
	{
		"name": "Erica G. Sandoval",
		"contactFrequency": "Weekly",
		"email": "eu@Inscelerisque.net",
		"phone": "1-989-956-5596",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "dui.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit",
		"company": "Massa Integer Vitae Industries",
		"title": "gravida"
	},
	{
		"name": "Noelle V. Howell",
		"contactFrequency": "BiWeekly",
		"email": "Sed.nulla@Duiselementum.co.uk",
		"phone": "1-255-158-6945",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "Proin",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Sem Eget Massa LLC",
		"title": "ultrices"
	},
	{
		"name": "Kaden Lopez",
		"contactFrequency": "Weekly",
		"email": "dapibus.quam.quis@inmolestie.com",
		"phone": "1-760-945-0863",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "vel",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Cursus Et Eros PC",
		"title": "sit"
	},
	{
		"name": "Lawrence Nielsen",
		"contactFrequency": "BiWeekly",
		"email": "ante.dictum.cursus@euismod.edu",
		"phone": "1-324-755-2315",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "vel",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Sodales Nisi Inc.",
		"title": "rhoncus"
	},
	{
		"name": "Judah Parsons",
		"contactFrequency": "None",
		"email": "ultrices.posuere@Mauris.ca",
		"phone": "1-662-899-0499",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "a",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Bibendum Ullamcorper Duis Inc.",
		"title": "Aliquam fringilla"
	},
	{
		"name": "Jayme N. Hamilton",
		"contactFrequency": "BiWeekly",
		"email": "elit@temporest.co.uk",
		"phone": "1-157-624-6944",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "luctus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Lorem Donec Corp.",
		"title": "litora torquent per"
	},
	{
		"name": "Keaton Q. Finley",
		"contactFrequency": "Yearly",
		"email": "pretium.et.rutrum@dictumeuplacerat.net",
		"phone": "1-790-200-7376",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "tellus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Nullam Associates",
		"title": "a feugiat"
	},
	{
		"name": "Tatum Acevedo",
		"contactFrequency": "Biannual",
		"email": "dictum.sapien.Aenean@tempusloremfringilla.co.uk",
		"phone": "1-461-726-3523",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "Duis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit",
		"company": "Nulla Corp.",
		"title": "pede. Suspendisse dui."
	},
	{
		"name": "Kenneth Bonner",
		"contactFrequency": "Quarterly",
		"email": "Nam.interdum.enim@eleifend.edu",
		"phone": "1-227-248-0169",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "dapibus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Risus Odio Consulting",
		"title": "malesuada"
	},
	{
		"name": "Dolan O. Griffith",
		"contactFrequency": "Monthly",
		"email": "in@lectus.org",
		"phone": "1-226-983-7378",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "Nulla",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Mauris Consulting",
		"title": "euismod enim."
	},
	{
		"name": "Herman B. Ingram",
		"contactFrequency": "None",
		"email": "amet@tellusimperdiet.co.uk",
		"phone": "1-928-686-1611",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "nisl",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Convallis Industries",
		"title": "odio. Aliquam"
	},
	{
		"name": "Gannon Schultz",
		"contactFrequency": "Quarterly",
		"email": "id.enim.Curabitur@etarcu.org",
		"phone": "1-405-113-3812",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "Nunc",
		"activeStatus": false,
		"notes": "Lorem ipsum",
		"company": "Eu Limited",
		"title": "eu sem."
	},
	{
		"name": "Bruno Valenzuela",
		"contactFrequency": "None",
		"email": "ullamcorper.velit@Aliquamornare.ca",
		"phone": "1-689-342-7454",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "magna.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Dolor Sit LLC",
		"title": "interdum. Curabitur"
	},
	{
		"name": "Quamar Q. Johnson",
		"contactFrequency": "Biannual",
		"email": "vehicula.et@rutrumjustoPraesent.org",
		"phone": "1-381-124-5191",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "Aliquam",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Odio LLC",
		"title": "sapien molestie"
	},
	{
		"name": "Camden Hood",
		"contactFrequency": "None",
		"email": "sapien.gravida.non@enimcondimentumeget.co.uk",
		"phone": "1-596-937-1323",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "in",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor",
		"company": "Donec Industries",
		"title": "nec"
	},
	{
		"name": "Inga B. Noel",
		"contactFrequency": "None",
		"email": "Mauris.vestibulum.neque@anteipsum.org",
		"phone": "1-523-306-0733",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "tellus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Scelerisque LLP",
		"title": "Ut sagittis"
	},
	{
		"name": "Bruno B. Stephens",
		"contactFrequency": "Quarterly",
		"email": "orci.adipiscing@Integertincidunt.com",
		"phone": "1-716-436-0094",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "torquent",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Massa Limited",
		"title": "et"
	},
	{
		"name": "Marsden W. Sullivan",
		"contactFrequency": "BiWeekly",
		"email": "vel.faucibus.id@felis.edu",
		"phone": "1-144-329-4631",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "risus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Sollicitudin Associates",
		"title": "accumsan laoreet ipsum."
	},
	{
		"name": "Mollie Ferrell",
		"contactFrequency": "Biannual",
		"email": "pretium.neque@mattis.edu",
		"phone": "1-390-273-4591",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "a",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Phasellus Vitae Mauris Incorporated",
		"title": "sem. Pellentesque ut"
	},
	{
		"name": "Leila Sims",
		"contactFrequency": "None",
		"email": "arcu.Morbi.sit@arcuvel.ca",
		"phone": "1-899-533-6952",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "lacus",
		"activeStatus": true,
		"notes": "Lorem",
		"company": "Non Vestibulum Nec Associates",
		"title": "Phasellus"
	},
	{
		"name": "Kermit K. Rivas",
		"contactFrequency": "Quarterly",
		"email": "odio.tristique.pharetra@idsapienCras.org",
		"phone": "1-356-678-1455",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "sagittis.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Cum Associates",
		"title": "facilisis eget,"
	},
	{
		"name": "Zahir Mueller",
		"contactFrequency": "BiWeekly",
		"email": "vel.est@neque.com",
		"phone": "1-720-710-7435",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "eu",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Ut Tincidunt Inc.",
		"title": "ipsum dolor"
	},
	{
		"name": "Faith I. Guerra",
		"contactFrequency": "Quarterly",
		"email": "condimentum.Donec@semegetmassa.edu",
		"phone": "1-708-882-3414",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "ac",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "In Consectetuer Ipsum Incorporated",
		"title": "consequat"
	},
	{
		"name": "Cruz E. Mann",
		"contactFrequency": "Yearly",
		"email": "dolor.Quisque.tincidunt@non.com",
		"phone": "1-417-469-3506",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "pellentesque,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Vivamus Nisi Mauris PC",
		"title": "ipsum"
	},
	{
		"name": "Zorita Green",
		"contactFrequency": "Quarterly",
		"email": "sit@Donec.org",
		"phone": "1-853-327-9946",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "enim.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "In Inc.",
		"title": "Cras convallis"
	},
	{
		"name": "Odysseus Berger",
		"contactFrequency": "Quarterly",
		"email": "Curabitur.massa@Nullamlobortis.com",
		"phone": "1-664-625-9842",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "massa.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Id Corp.",
		"title": "id ante dictum"
	},
	{
		"name": "Alexander Haynes",
		"contactFrequency": "Quarterly",
		"email": "netus.et.malesuada@risus.co.uk",
		"phone": "1-646-437-5095",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "Fusce",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Semper Institute",
		"title": "pede. Suspendisse dui."
	},
	{
		"name": "Noel H. Patton",
		"contactFrequency": "None",
		"email": "vitae@Donec.com",
		"phone": "1-713-193-0628",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "dictum",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit",
		"company": "Et Magnis Limited",
		"title": "felis"
	},
	{
		"name": "Jamal J. Crawford",
		"contactFrequency": "Quarterly",
		"email": "erat@mauris.com",
		"phone": "1-258-703-2904",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "sem",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Ut Sem Institute",
		"title": "vulputate velit"
	},
	{
		"name": "Preston Y. Hood",
		"contactFrequency": "Weekly",
		"email": "nunc.sit.amet@urnaUttincidunt.org",
		"phone": "1-797-968-0307",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "Nulla",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Arcu Sed Institute",
		"title": "turpis. Nulla"
	},
	{
		"name": "Ginger D. Roberson",
		"contactFrequency": "BiWeekly",
		"email": "mi@penatibuset.edu",
		"phone": "1-336-507-4887",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "luctus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Metus Aliquam Erat Industries",
		"title": "eu"
	},
	{
		"name": "Jesse W. Russell",
		"contactFrequency": "BiWeekly",
		"email": "Mauris.vestibulum@sed.edu",
		"phone": "1-535-349-2365",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "tellus.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Gravida Institute",
		"title": "a nunc."
	},
	{
		"name": "Kyle Good",
		"contactFrequency": "Weekly",
		"email": "tortor@a.ca",
		"phone": "1-992-615-4725",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "malesuada",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Placerat Velit LLC",
		"title": "et magnis"
	},
	{
		"name": "Kennan V. Randall",
		"contactFrequency": "BiWeekly",
		"email": "at.sem.molestie@velitegetlaoreet.edu",
		"phone": "1-671-276-5303",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "tellus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Auctor Vitae Consulting",
		"title": "ridiculus mus."
	},
	{
		"name": "Axel Odom",
		"contactFrequency": "Yearly",
		"email": "nisi@non.edu",
		"phone": "1-862-608-5096",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "erat",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Feugiat Lorem PC",
		"title": "sodales elit erat"
	},
	{
		"name": "Xander Cummings",
		"contactFrequency": "Yearly",
		"email": "velit.eget.laoreet@placerat.co.uk",
		"phone": "1-546-405-8521",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "eu",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "In Molestie Tortor LLP",
		"title": "amet diam"
	},
	{
		"name": "Pearl O. Duran",
		"contactFrequency": "Biannual",
		"email": "feugiat.placerat@tacitisociosqu.net",
		"phone": "1-236-238-4446",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "ultricies",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Eget Laoreet Posuere LLP",
		"title": "amet diam eu"
	},
	{
		"name": "Ivor E. Abbott",
		"contactFrequency": "None",
		"email": "non.nisi.Aenean@Mauris.org",
		"phone": "1-145-336-5511",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "volutpat.",
		"activeStatus": true,
		"notes": "Lorem",
		"company": "Nec Mauris Blandit Industries",
		"title": "a"
	},
	{
		"name": "Hammett S. Cruz",
		"contactFrequency": "None",
		"email": "iaculis.enim.sit@dolorNulla.com",
		"phone": "1-359-399-4296",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "ac",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Velit LLP",
		"title": "In"
	},
	{
		"name": "Kasimir Workman",
		"contactFrequency": "Quarterly",
		"email": "nec.urna@ornarelectus.ca",
		"phone": "1-209-437-5361",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "nonummy",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Eleifend Associates",
		"title": "accumsan"
	},
	{
		"name": "Lydia Hardin",
		"contactFrequency": "Weekly",
		"email": "tristique.senectus.et@dolorDonec.co.uk",
		"phone": "1-495-540-5063",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "orci.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Hendrerit Industries",
		"title": "Sed"
	},
	{
		"name": "Jonas A. Weeks",
		"contactFrequency": "Biannual",
		"email": "nunc.risus@velitduisemper.org",
		"phone": "1-626-685-3652",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "tempor",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit",
		"company": "Est Nunc LLP",
		"title": "lobortis, nisi nibh"
	},
	{
		"name": "Alexa Wilkins",
		"contactFrequency": "Weekly",
		"email": "neque.Nullam@Etiam.co.uk",
		"phone": "1-853-584-0665",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "at",
		"activeStatus": true,
		"notes": "Lorem",
		"company": "Nullam Foundation",
		"title": "gravida sit"
	},
	{
		"name": "Roanna Shaffer",
		"contactFrequency": "Quarterly",
		"email": "sed.libero@infaucibusorci.co.uk",
		"phone": "1-875-140-5248",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "enim,",
		"activeStatus": true,
		"notes": "Lorem",
		"company": "Nulla Ante Iaculis Associates",
		"title": "et ultrices"
	},
	{
		"name": "Desiree X. White",
		"contactFrequency": "None",
		"email": "non@tortor.com",
		"phone": "1-360-786-5065",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "blandit.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Blandit Inc.",
		"title": "est."
	},
	{
		"name": "Tate Z. Kelly",
		"contactFrequency": "BiWeekly",
		"email": "Sed@eget.net",
		"phone": "1-131-546-8221",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "mauris.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Ridiculus PC",
		"title": "Duis"
	},
	{
		"name": "Gage Q. Alford",
		"contactFrequency": "None",
		"email": "Maecenas.malesuada.fringilla@lectusconvallisest.com",
		"phone": "1-234-529-8704",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "diam",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Integer Id Magna Consulting",
		"title": "diam dictum sapien."
	},
	{
		"name": "Tate T. Moses",
		"contactFrequency": "Monthly",
		"email": "ipsum@felispurus.com",
		"phone": "1-297-420-1263",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "rutrum",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Luctus Sit Amet Institute",
		"title": "dictum"
	},
	{
		"name": "Zenia Cox",
		"contactFrequency": "BiWeekly",
		"email": "erat.eget@Inmi.ca",
		"phone": "1-294-584-7950",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "imperdiet",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Sodales Elit PC",
		"title": "Aliquam"
	},
	{
		"name": "Adara E. Kirby",
		"contactFrequency": "Monthly",
		"email": "rhoncus.id.mollis@anteiaculisnec.co.uk",
		"phone": "1-229-570-3107",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "taciti",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit",
		"company": "Eget Venenatis A Corp.",
		"title": "Vestibulum ut eros"
	}
]


/////  SCRIPT  //////

function randomDate(start, end) {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
}


const initialCount = db.contacts.count();

for (let i = 0; i < 100; i += 1) {

  const id = initialCount + i + 1;
  const name = mockData[i].name;
  const contactFrequency = mockData[i].contactFrequency;
  const email = mockData[i].email;
  const phone = mockData[i].phone;
  const LinkedIn = mockData[i].LinkedIn + name;
  const priority = mockData[i].priority;
  const familiarity = mockData[i].familiarity;
  const contextSpace = mockData[i].contextSpace;
  const activeStatus = mockData[i].activeStatus;
  // Generate date between 2001 and present
  const lastContactDate = randomDate(new Date(2001, 0, 1), new Date());
  const notes = mockData[i].notes;
  const company = mockData[i].company;
  // Generate date between today and 2 years from today
  const nextContactDate = randomDate(lastContactDate, new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 730));
  const title = mockData[i].title + `${i}`;

  // const randomCreatedDate = (new Date())
  //   - Math.floor(Math.random() * 60) * 1000 * 60 * 60 * 24;
  // const created = new Date(randomCreatedDate);
  // const randomDueDate = (new Date())
  //   - Math.floor(Math.random() * 60) * 1000 * 60 * 60 * 24;
  // const due = new Date(randomDueDate);

  // const owner = owners[Math.floor(Math.random() * 5)];
  // const status = statuses[Math.floor(Math.random() * 4)];
  // const effort = Math.ceil(Math.random() * 20);
  // const title = `Lorem ipsum dolor sit amet, ${i}`;
  // const id = initialCount + i + 1;

  const contact = {
    id, 
    name, 
    contactFrequency, 
    email, 
    phone, 
    LinkedIn, 
    priority,
    familiarity,
    contextSpace,
    activeStatus,
    lastContactDate,
    notes,
    company,
    nextContactDate,
    title,
  };

  db.contacts.insertOne(contact);
}

const count = db.contacts.count();
db.counters.update({ _id: 'contacts' }, { $set: { current: count } });

print('New contacts count:', count);
