// import {mockData} from './mockdata.js';

/* global db print */
/* eslint no-restricted-globals: "off" */


////https://www.generatedata.com/

const mockData =[
	{
		"name": "Alma Lowe",
		"contactFrequency": "Biweekly",
		"email": "non.massa@convalliserat.com",
		"phone": "4375476705",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "mauris",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Est Nunc Ullamcorper Corporation",
		"title": "pellentesque a, facilisis"
	},
	{
		"name": "Driscoll Rollins",
		"contactFrequency": "None",
		"email": "et@quamelementumat.org",
		"phone": "1674435169",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "urna",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Magna Ltd",
		"title": "lorem,"
	},
	{
		"name": "Benedict Torres",
		"contactFrequency": "None",
		"email": "Cras.interdum@euelitNulla.com",
		"phone": "7564030777",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "tellus.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Quam Pellentesque Industries",
		"title": "ac"
	},
	{
		"name": "Aaron Jones",
		"contactFrequency": "Biweekly",
		"email": "tellus@velit.edu",
		"phone": "2528311942",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "arcu",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Lacus Associates",
		"title": "dignissim"
	},
	{
		"name": "Stephen Fleming",
		"contactFrequency": "Yearly",
		"email": "In.nec@Maecenasiaculisaliquet.net",
		"phone": "6727300293",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "varius",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit",
		"company": "Viverra Company",
		"title": "aliquet magna"
	},
	{
		"name": "Ivory Fuller",
		"contactFrequency": "Biannual",
		"email": "Cras@necmauris.edu",
		"phone": "7961457772",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "dui",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Dui Semper Et Corp.",
		"title": "est. Mauris"
	},
	{
		"name": "Hammett Ratliff",
		"contactFrequency": "Biannual",
		"email": "Sed.nec@at.edu",
		"phone": "6334954118",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "interdum.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Convallis LLP",
		"title": "volutpat"
	},
	{
		"name": "Brody Mckenzie",
		"contactFrequency": "Monthly",
		"email": "auctor.velit@adipiscingenim.org",
		"phone": "8523054736",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "elementum",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Augue Malesuada LLC",
		"title": "imperdiet ornare."
	},
	{
		"name": "Iola Kelly",
		"contactFrequency": "Biannual",
		"email": "molestie@fringillaeuismodenim.com",
		"phone": "2683814583",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "varius",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Vivamus Euismod Urna Foundation",
		"title": "leo."
	},
	{
		"name": "Alika Floyd",
		"contactFrequency": "Yearly",
		"email": "Nullam@interdumSed.net",
		"phone": "4748021516",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "libero.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Integer Vitae Foundation",
		"title": "ut mi. Duis"
	},
	{
		"name": "Victoria Rutledge",
		"contactFrequency": "Monthly",
		"email": "sem.semper@idmagnaet.edu",
		"phone": "6030309199",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "Donec",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Tempus Company",
		"title": "ultricies"
	},
	{
		"name": "Candice George",
		"contactFrequency": "Quarterly",
		"email": "nisi@sapien.org",
		"phone": "2177670551",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "eu",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Curabitur Incorporated",
		"title": "scelerisque"
	},
	{
		"name": "Travis King",
		"contactFrequency": "Biannual",
		"email": "est.ac.facilisis@Nunclectuspede.edu",
		"phone": "2631437606",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "Duis",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Nec Limited",
		"title": "tincidunt"
	},
	{
		"name": "Patience Odom",
		"contactFrequency": "Quarterly",
		"email": "scelerisque@felisadipiscingfringilla.com",
		"phone": "8717989440",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "tristique",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Scelerisque LLC",
		"title": "libero est, congue"
	},
	{
		"name": "Demetrius Hickman",
		"contactFrequency": "Biannual",
		"email": "viverra@temporbibendumDonec.co.uk",
		"phone": "6509089854",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "orci",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Cursus Et Magna LLP",
		"title": "Mauris magna."
	},
	{
		"name": "Kim Roth",
		"contactFrequency": "Biweekly",
		"email": "Proin@Quisque.edu",
		"phone": "4545235628",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "sodales",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Dapibus Quam Quis Company",
		"title": "vehicula risus. Nulla"
	},
	{
		"name": "Drake Fitzpatrick",
		"contactFrequency": "Biweekly",
		"email": "natoque.penatibus.et@sedduiFusce.edu",
		"phone": "2222675336",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "arcu",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Commodo Inc.",
		"title": "velit eget"
	},
	{
		"name": "Sharon Alvarado",
		"contactFrequency": "Custom",
		"email": "nulla.Integer.urna@orcilacusvestibulum.com",
		"phone": "6415892875",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "ipsum.",
		"activeStatus": true,
		"notes": "Lorem ipsum",
		"company": "Dictum Ultricies Ligula Corporation",
		"title": "amet risus. Donec"
	},
	{
		"name": "Angelica Tyson",
		"contactFrequency": "Weekly",
		"email": "id.ante@orciDonecnibh.com",
		"phone": "5712378183",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Duis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Feugiat Company",
		"title": "lacus. Cras interdum."
	},
	{
		"name": "Sebastian Barton",
		"contactFrequency": "Quarterly",
		"email": "consequat.enim@arcu.edu",
		"phone": "9975198366",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Quisque",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor",
		"company": "Nunc Quis Associates",
		"title": "neque"
	},
	{
		"name": "Chastity Sloan",
		"contactFrequency": "Biweekly",
		"email": "Suspendisse.sed.dolor@eu.ca",
		"phone": "6397426872",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "Nam",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Faucibus Ut Industries",
		"title": "velit. Pellentesque ultricies"
	},
	{
		"name": "Kiayada Knight",
		"contactFrequency": "Biweekly",
		"email": "Proin.non@Sedmolestie.net",
		"phone": "9353699246",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "ut",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Eu LLC",
		"title": "sociis natoque"
	},
	{
		"name": "Rina Carlson",
		"contactFrequency": "Weekly",
		"email": "aliquam@magna.ca",
		"phone": "1802371038",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "cubilia",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Nulla LLP",
		"title": "et ipsum"
	},
	{
		"name": "Forrest Mcmahon",
		"contactFrequency": "Biweekly",
		"email": "iaculis.quis.pede@Suspendisse.org",
		"phone": "2529335585",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "nunc",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Eget Ipsum Suspendisse Company",
		"title": "fringilla. Donec feugiat"
	},
	{
		"name": "Hedy Morgan",
		"contactFrequency": "Weekly",
		"email": "arcu@elitsedconsequat.edu",
		"phone": "3525854578",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "egestas.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Vitae Sodales Associates",
		"title": "lacus. Quisque purus"
	},
	{
		"name": "Frances Hogan",
		"contactFrequency": "Biweekly",
		"email": "Quisque.tincidunt.pede@idante.co.uk",
		"phone": "6954989716",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "sit",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Quis Arcu Vel Associates",
		"title": "id"
	},
	{
		"name": "Kelly Howe",
		"contactFrequency": "Monthly",
		"email": "vulputate@vitae.org",
		"phone": "7514574496",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "velit",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Elit Pretium Et PC",
		"title": "parturient montes, nascetur"
	},
	{
		"name": "Risa Ross",
		"contactFrequency": "Biweekly",
		"email": "neque.Morbi.quis@sodalespurusin.co.uk",
		"phone": "1848523818",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "eleifend",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Risus A Ultricies Institute",
		"title": "Cras lorem lorem,"
	},
	{
		"name": "Griffin Olson",
		"contactFrequency": "Biannual",
		"email": "erat.eget.ipsum@utdolor.org",
		"phone": "4227592099",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "convallis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Natoque PC",
		"title": "eu, odio. Phasellus"
	},
	{
		"name": "Carl Cotton",
		"contactFrequency": "Weekly",
		"email": "Fusce.mollis.Duis@tempor.edu",
		"phone": "2252853817",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "diam",
		"activeStatus": true,
		"notes": "Lorem",
		"company": "Nullam Corporation",
		"title": "tellus sem"
	},
	{
		"name": "Irma Perez",
		"contactFrequency": "Yearly",
		"email": "eu.euismod.ac@loremtristiquealiquet.net",
		"phone": "4214450760",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "rhoncus.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Sed Orci Lobortis Corp.",
		"title": "Phasellus"
	},
	{
		"name": "Castor Wheeler",
		"contactFrequency": "Weekly",
		"email": "non.lobortis@leoelementum.com",
		"phone": "6140808201",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "eget",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor",
		"company": "Elit A Feugiat LLP",
		"title": "nisi"
	},
	{
		"name": "Alexa Pitts",
		"contactFrequency": "Custom",
		"email": "scelerisque.neque.sed@anteiaculis.net",
		"phone": "8283061413",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "id",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "A Auctor Non Limited",
		"title": "aliquam, enim"
	},
	{
		"name": "Rajah Lester",
		"contactFrequency": "Yearly",
		"email": "Duis.gravida.Praesent@mauris.org",
		"phone": "8656674375",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "vehicula",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "In Dolor Ltd",
		"title": "sed dui. Fusce"
	},
	{
		"name": "Fulton Romero",
		"contactFrequency": "Yearly",
		"email": "elementum.at.egestas@blanditviverraDonec.co.uk",
		"phone": "5752370573",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "eleifend",
		"activeStatus": false,
		"notes": "Lorem ipsum",
		"company": "Aliquet Metus Company",
		"title": "tempus,"
	},
	{
		"name": "Edan Riddle",
		"contactFrequency": "Yearly",
		"email": "eu.turpis@euismodurna.com",
		"phone": "9793229585",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "tempor",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Egestas Fusce Aliquet PC",
		"title": "mollis"
	},
	{
		"name": "Vanna Short",
		"contactFrequency": "Biweekly",
		"email": "vulputate@rhoncus.edu",
		"phone": "2793334254",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "Ut",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Adipiscing Ligula Foundation",
		"title": "sit amet"
	},
	{
		"name": "Warren Harmon",
		"contactFrequency": "Quarterly",
		"email": "adipiscing@pretium.net",
		"phone": "2283931180",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "turpis",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Tristique Neque Industries",
		"title": "risus."
	},
	{
		"name": "Shaeleigh Chaney",
		"contactFrequency": "Quarterly",
		"email": "Donec.fringilla.Donec@estcongue.net",
		"phone": "9556843015",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "mattis",
		"activeStatus": false,
		"notes": "Lorem",
		"company": "Morbi Limited",
		"title": "ipsum leo elementum"
	},
	{
		"name": "Neil Tate",
		"contactFrequency": "None",
		"email": "rhoncus.id@accumsan.co.uk",
		"phone": "2656982963",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "pellentesque.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Dictum Sapien LLC",
		"title": "lorem vitae"
	},
	{
		"name": "Yvette Ryan",
		"contactFrequency": "Biweekly",
		"email": "sagittis.Duis@commodotincidunt.net",
		"phone": "8622837251",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "adipiscing",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Egestas A Limited",
		"title": "eu tellus"
	},
	{
		"name": "Colton York",
		"contactFrequency": "Biweekly",
		"email": "adipiscing@tempus.org",
		"phone": "3450447218",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "sagittis",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Aptent Taciti Sociosqu Inc.",
		"title": "nibh dolor,"
	},
	{
		"name": "Jillian Lawrence",
		"contactFrequency": "None",
		"email": "varius.ultrices@atauctorullamcorper.org",
		"phone": "2179477374",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "pharetra",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Dictum Proin Ltd",
		"title": "Nullam"
	},
	{
		"name": "Jonas Rodgers",
		"contactFrequency": "Biannual",
		"email": "aliquet.diam.Sed@sit.net",
		"phone": "1648796185",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "sociis",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Risus Odio Company",
		"title": "lorem semper auctor."
	},
	{
		"name": "Keane Pratt",
		"contactFrequency": "Quarterly",
		"email": "elit.Etiam@facilisis.edu",
		"phone": "1420077406",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "urna,",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Vulputate Velit Eu Inc.",
		"title": "sem, vitae aliquam"
	},
	{
		"name": "Gil Bonner",
		"contactFrequency": "Weekly",
		"email": "augue.scelerisque@Cras.co.uk",
		"phone": "1217387624",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Nunc",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Vel Est PC",
		"title": "magna"
	},
	{
		"name": "Galvin Rivas",
		"contactFrequency": "Custom",
		"email": "mauris.rhoncus.id@Morbineque.edu",
		"phone": "8183210217",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "lobortis",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Vitae Semper Egestas Company",
		"title": "dolor"
	},
	{
		"name": "Riley Benton",
		"contactFrequency": "None",
		"email": "accumsan.sed.facilisis@sapien.co.uk",
		"phone": "6901861155",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Nunc",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Phasellus Dolor Elit Institute",
		"title": "tristique pellentesque, tellus"
	},
	{
		"name": "Porter Marsh",
		"contactFrequency": "Monthly",
		"email": "penatibus.et.magnis@nequeIn.co.uk",
		"phone": "3575610970",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "felis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Turpis Incorporated",
		"title": "arcu. Curabitur"
	},
	{
		"name": "Quail Bender",
		"contactFrequency": "Yearly",
		"email": "tempus.lorem@dignissimMaecenasornare.com",
		"phone": "4434145394",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "neque.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor",
		"company": "Dis Parturient Montes Ltd",
		"title": "non"
	},
	{
		"name": "Inez Owens",
		"contactFrequency": "Biweekly",
		"email": "Ut@magna.co.uk",
		"phone": "7066693667",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "orci",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Lacus Etiam Institute",
		"title": "ultricies ornare, elit"
	},
	{
		"name": "Gary Bryant",
		"contactFrequency": "None",
		"email": "odio.vel.est@Cras.edu",
		"phone": "2817172397",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "elementum",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit",
		"company": "Eu Nibh Vulputate Institute",
		"title": "nibh dolor, nonummy"
	},
	{
		"name": "Courtney Bryan",
		"contactFrequency": "Custom",
		"email": "elementum.at@magnanec.ca",
		"phone": "7345717076",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "gravida",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Donec Sollicitudin Adipiscing LLC",
		"title": "ultrices posuere cubilia"
	},
	{
		"name": "Baker Hull",
		"contactFrequency": "Biweekly",
		"email": "mi.enim@Duis.edu",
		"phone": "8821005917",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "egestas.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Curabitur Vel Incorporated",
		"title": "nec tempus scelerisque,"
	},
	{
		"name": "Buffy Valentine",
		"contactFrequency": "Custom",
		"email": "est.mauris@velit.net",
		"phone": "7302958062",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "vulputate",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Risus Donec Corporation",
		"title": "arcu"
	},
	{
		"name": "Quintessa Sheppard",
		"contactFrequency": "Biannual",
		"email": "Maecenas.iaculis@Donectemporest.com",
		"phone": "2887482583",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Etiam",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "At LLP",
		"title": "ut nisi a"
	},
	{
		"name": "Candace Burns",
		"contactFrequency": "Weekly",
		"email": "interdum.ligula@in.co.uk",
		"phone": "2599099824",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "mi",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Id Erat Etiam Foundation",
		"title": "luctus vulputate, nisi"
	},
	{
		"name": "Kylie Eaton",
		"contactFrequency": "Biweekly",
		"email": "faucibus.orci.luctus@amet.net",
		"phone": "3034711866",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "eget",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "A Facilisis Non Industries",
		"title": "dictum. Phasellus in"
	},
	{
		"name": "Dillon Baird",
		"contactFrequency": "Quarterly",
		"email": "ornare.libero@pede.net",
		"phone": "9777971843",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "et",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Phasellus Nulla PC",
		"title": "dictum. Proin"
	},
	{
		"name": "Idona Moon",
		"contactFrequency": "Biannual",
		"email": "commodo.at.libero@iaculisodioNam.edu",
		"phone": "3661518956",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "aliquet",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Ultrices Inc.",
		"title": "penatibus et magnis"
	},
	{
		"name": "Kermit Newman",
		"contactFrequency": "Custom",
		"email": "vulputate@liberoProin.com",
		"phone": "5992988785",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "a",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Amet Institute",
		"title": "nec"
	},
	{
		"name": "Xavier Glass",
		"contactFrequency": "Biweekly",
		"email": "venenatis.vel@temporbibendumDonec.com",
		"phone": "9981555825",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Cras",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Duis Corp.",
		"title": "nulla ante,"
	},
	{
		"name": "Clark Santiago",
		"contactFrequency": "Biannual",
		"email": "ipsum@sapien.com",
		"phone": "8423905929",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "dapibus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Cursus Diam Limited",
		"title": "eu enim."
	},
	{
		"name": "Fuller Rowland",
		"contactFrequency": "Weekly",
		"email": "magna@risusodio.edu",
		"phone": "7284537688",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "imperdiet",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor",
		"company": "Convallis Est Vitae PC",
		"title": "tempor"
	},
	{
		"name": "Myra Mccarthy",
		"contactFrequency": "Biweekly",
		"email": "condimentum@eget.net",
		"phone": "9236604528",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "senectus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Sagittis Semper Nam Consulting",
		"title": "ligula"
	},
	{
		"name": "Phelan Harris",
		"contactFrequency": "Biannual",
		"email": "vulputate.eu.odio@Sednuncest.edu",
		"phone": "5653589939",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Quisque",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Turpis Nulla Aliquet Institute",
		"title": "mauris."
	},
	{
		"name": "Asher Pratt",
		"contactFrequency": "None",
		"email": "et@eusemPellentesque.co.uk",
		"phone": "6854865205",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "risus.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Enim Curabitur Ltd",
		"title": "nibh."
	},
	{
		"name": "Ella Richmond",
		"contactFrequency": "Quarterly",
		"email": "non@dignissimpharetraNam.edu",
		"phone": "3845867457",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "sociis",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Mollis Lectus Institute",
		"title": "sociis natoque penatibus"
	},
	{
		"name": "Emmanuel Ferrell",
		"contactFrequency": "Custom",
		"email": "risus@eueuismodac.com",
		"phone": "3716620989",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "quis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Phasellus In Felis Foundation",
		"title": "et"
	},
	{
		"name": "Eugenia Brock",
		"contactFrequency": "Weekly",
		"email": "ante.Nunc.mauris@dolor.ca",
		"phone": "8949245423",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "tempus",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Purus Ac Tellus Corp.",
		"title": "odio semper cursus."
	},
	{
		"name": "Leah Odom",
		"contactFrequency": "Biannual",
		"email": "arcu@dui.org",
		"phone": "4472295153",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "lacus.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Ante Inc.",
		"title": "arcu. Vestibulum"
	},
	{
		"name": "Lucius Petersen",
		"contactFrequency": "Biweekly",
		"email": "est@Donecfringilla.net",
		"phone": "8486996394",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "eget",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor",
		"company": "Nisl Ltd",
		"title": "Sed congue, elit"
	},
	{
		"name": "Alfreda Malone",
		"contactFrequency": "Biannual",
		"email": "pellentesque.tellus@interdum.ca",
		"phone": "5543587124",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "mauris",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Risus Donec Egestas Inc.",
		"title": "tellus id nunc"
	},
	{
		"name": "Mollie William",
		"contactFrequency": "Weekly",
		"email": "sed.hendrerit.a@Aenean.edu",
		"phone": "3893391962",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "erat",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Eleifend Cras Sed Ltd",
		"title": "eget ipsum."
	},
	{
		"name": "Christian Small",
		"contactFrequency": "Yearly",
		"email": "In@magna.com",
		"phone": "6288897536",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Praesent",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Auctor Velit Eget Associates",
		"title": "mi tempor lorem,"
	},
	{
		"name": "Orli Lynn",
		"contactFrequency": "None",
		"email": "amet@erosturpis.co.uk",
		"phone": "8308861873",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "tellus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Vitae Sodales At LLC",
		"title": "nisl. Maecenas"
	},
	{
		"name": "Ashton Rivers",
		"contactFrequency": "None",
		"email": "eu.nibh@enimnisl.edu",
		"phone": "5640579669",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "id",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Lacus Company",
		"title": "semper auctor. Mauris"
	},
	{
		"name": "Nero Gross",
		"contactFrequency": "Weekly",
		"email": "pede.ultrices.a@facilisis.net",
		"phone": "8953275008",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "eleifend",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "Neque Nullam Nisl Limited",
		"title": "parturient montes,"
	},
	{
		"name": "Zorita Gomez",
		"contactFrequency": "Custom",
		"email": "Sed.et@elitafeugiat.net",
		"phone": "1314474912",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "commodo",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Aliquet Sem Consulting",
		"title": "Quisque varius."
	},
	{
		"name": "Edward Oneill",
		"contactFrequency": "Yearly",
		"email": "Integer.aliquam.adipiscing@egestasurnajusto.net",
		"phone": "6893015700",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Sed",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Consequat Lectus Institute",
		"title": "sollicitudin a, malesuada"
	},
	{
		"name": "Clio Washington",
		"contactFrequency": "Quarterly",
		"email": "Donec.at@pedemalesuada.edu",
		"phone": "1173375239",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "lorem",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Nisi Aenean Incorporated",
		"title": "egestas"
	},
	{
		"name": "Sybill Ratliff",
		"contactFrequency": "Weekly",
		"email": "eget.ipsum@orci.ca",
		"phone": "8594676289",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "Integer",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Nulla Ante Iaculis Company",
		"title": "Cum sociis natoque"
	},
	{
		"name": "Keith Lamb",
		"contactFrequency": "Monthly",
		"email": "Mauris@Aeneaneget.edu",
		"phone": "9320634796",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "mauris.",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit",
		"company": "Tempor Corporation",
		"title": "dignissim magna"
	},
	{
		"name": "Indira Townsend",
		"contactFrequency": "None",
		"email": "dictum.Phasellus@eunibh.com",
		"phone": "3380812589",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "eu",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Eget Corp.",
		"title": "nunc"
	},
	{
		"name": "Stacy Olsen",
		"contactFrequency": "Quarterly",
		"email": "Donec@necurnasuscipit.net",
		"phone": "9546682671",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "dictum.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Consectetuer Mauris Id Associates",
		"title": "dapibus"
	},
	{
		"name": "Raven Erickson",
		"contactFrequency": "Monthly",
		"email": "sed.dolor.Fusce@in.com",
		"phone": "3842358868",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "odio,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Erat Vel Company",
		"title": "lacus vestibulum lorem,"
	},
	{
		"name": "Kaden Villarreal",
		"contactFrequency": "Biweekly",
		"email": "Etiam.gravida@ipsumprimisin.net",
		"phone": "4962964764",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "accumsan",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Libero Ltd",
		"title": "Donec"
	},
	{
		"name": "Edan Landry",
		"contactFrequency": "Weekly",
		"email": "felis.adipiscing@nequevitae.edu",
		"phone": "8671118860",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "risus.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor",
		"company": "Ac Turpis Egestas Incorporated",
		"title": "hendrerit"
	},
	{
		"name": "Blaze Finley",
		"contactFrequency": "Biweekly",
		"email": "ut.aliquam.iaculis@disparturient.net",
		"phone": "7577753561",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "vitae,",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Ipsum Non Institute",
		"title": "orci quis"
	},
	{
		"name": "Jaden Mann",
		"contactFrequency": "Biweekly",
		"email": "Integer.id@velit.co.uk",
		"phone": "3822486410",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "facilisis",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Tempor Bibendum Corp.",
		"title": "Nunc laoreet"
	},
	{
		"name": "MacKensie Wilson",
		"contactFrequency": "Quarterly",
		"email": "augue@ultricessitamet.ca",
		"phone": "4157063117",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "mauris",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Eget Venenatis LLC",
		"title": "ullamcorper. Duis"
	},
	{
		"name": "Amal Abbott",
		"contactFrequency": "Yearly",
		"email": "turpis.In@eulacus.co.uk",
		"phone": "4755707751",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Donec",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Lacinia Sed Congue Incorporated",
		"title": "nibh"
	},
	{
		"name": "Kennedy Ramos",
		"contactFrequency": "Biweekly",
		"email": "congue.a.aliquet@interdumSed.co.uk",
		"phone": "7629314267",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "felis.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Ullamcorper Magna Limited",
		"title": "Sed pharetra,"
	},
	{
		"name": "Lamar Olsen",
		"contactFrequency": "Monthly",
		"email": "Nunc.lectus@Nullamscelerisque.org",
		"phone": "3142153024",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "consectetuer",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Arcu Eu Foundation",
		"title": "ornare,"
	},
	{
		"name": "Wylie Guerra",
		"contactFrequency": "Weekly",
		"email": "natoque.penatibus.et@magna.edu",
		"phone": "7065161643",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "cursus",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Blandit Corporation",
		"title": "sem semper erat,"
	},
	{
		"name": "Dylan Gordon",
		"contactFrequency": "Biannual",
		"email": "luctus@egetmagna.ca",
		"phone": "8107185597",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "sagittis",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Nunc In At Ltd",
		"title": "Proin"
	},
	{
		"name": "Harlan Ryan",
		"contactFrequency": "Quarterly",
		"email": "eros.nec@elementumsem.edu",
		"phone": "6790775396",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "parturient",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Malesuada Integer Id Ltd",
		"title": "vitae semper egestas,"
	},
	{
		"name": "Alexandra Kane",
		"contactFrequency": "Yearly",
		"email": "ac@mitemporlorem.net",
		"phone": "5093536449",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "blandit",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Euismod Inc.",
		"title": "Nam"
	},
	{
		"name": "Chancellor Hendricks",
		"contactFrequency": "None",
		"email": "vel.quam@vestibulum.com",
		"phone": "1341300355",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "lacus.",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Ornare Tortor At Limited",
		"title": "diam at"
	},
	{
		"name": "Vance Blevins",
		"contactFrequency": "Quarterly",
		"email": "enim@lorem.com",
		"phone": "6079875827",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "justo",
		"activeStatus": false,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Mi Lacinia Mattis PC",
		"title": "sodales nisi"
	}
]


/////  SCRIPT  //////

function randomDate(start, end) {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
}


const initialCount = db.contacts.count();

for (let i = 0; i < 100; i += 1) {

  const id = initialCount + i + 1;
  const name = mockData[i].name;
  const contactFrequency = mockData[i].contactFrequency;
  const email = mockData[i].email;
  const phone = mockData[i].phone;
  const LinkedIn = mockData[i].LinkedIn + name;
  const priority = mockData[i].priority;
  const familiarity = mockData[i].familiarity;
  const contextSpace = mockData[i].contextSpace;
  const activeStatus = mockData[i].activeStatus;
  // Generate date between 2001 and present
  const lastContactDate = randomDate(new Date(2001, 0, 1), new Date());
  const notes = mockData[i].notes;
  const company = mockData[i].company;
  // Generate date between today and 2 years from today
  const nextContactDate = randomDate(new Date(), new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 730));
  const title = mockData[i].title + `${i}`;

  const contact = {
    id, 
    name, 
    contactFrequency, 
    email, 
    phone, 
    LinkedIn, 
    priority,
    familiarity,
    contextSpace,
    activeStatus,
    lastContactDate,
    notes,
    company,
    nextContactDate,
    title,
  };

  db.contacts.insertOne(contact);
}

const count = db.contacts.count();
db.counters.update({ _id: 'contacts' }, { $set: { current: count } });

print('New contacts count:', count);
