// import {mockData} from './mockdata.js';

/* global db print */
/* eslint no-restricted-globals: "off" */


////https://www.generatedata.com/

const mockData =[
	{
		"name": "Abdul Madden",
		"contactFrequency": "Custom",
		"email": "commodo.auctor@Quisque.net",
		"phone": "9447681159",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "mauris.",
		"activeStatus": false,
		"notes": "eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id,",
		"company": "Auctor Limited",
		"title": "justo. Proin non",
		"priority": "high"
	},
	{
		"name": "Dahlia Woods",
		"contactFrequency": "Yearly",
		"email": "facilisi.Sed@ornare.co.uk",
		"phone": "4025101431",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Aenean",
		"activeStatus": false,
		"notes": "ornare tortor at risus. Nunc ac sem",
		"company": "Risus Quis Diam Institute",
		"title": "malesuada ut,",
		"priority": "low"
	},
	{
		"name": "Destiny Morrison",
		"contactFrequency": "Biannual",
		"email": "Cum@acrisusMorbi.co.uk",
		"phone": "4869035988",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "in",
		"activeStatus": true,
		"notes": "Nunc pulvinar arcu et pede. Nunc sed orci",
		"company": "Non Quam Pellentesque Incorporated",
		"title": "magna.",
		"priority": "medium"
	},
	{
		"name": "Dieter Kramer",
		"contactFrequency": "Custom",
		"email": "fringilla.mi@quam.ca",
		"phone": "6237947037",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "primis",
		"activeStatus": false,
		"notes": "lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare,",
		"company": "In Incorporated",
		"title": "Aenean",
		"priority": "medium"
	},
	{
		"name": "Noble Hanson",
		"contactFrequency": "None",
		"email": "eu.erat.semper@Uttinciduntorci.com",
		"phone": "5726609475",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "inceptos",
		"activeStatus": true,
		"notes": "dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus",
		"company": "Ipsum Leo Elementum Limited",
		"title": "ornare sagittis felis.",
		"priority": "low"
	},
	{
		"name": "Beau Marquez",
		"contactFrequency": "None",
		"email": "Maecenas.libero.est@Sed.co.uk",
		"phone": "2328508314",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "nisi",
		"activeStatus": false,
		"notes": "at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus.",
		"company": "Eu Incorporated",
		"title": "augue ut lacus.",
		"priority": "low"
	},
	{
		"name": "Dara Salas",
		"contactFrequency": "Quarterly",
		"email": "Nam.consequat.dolor@semperrutrumFusce.com",
		"phone": "5393633585",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "In",
		"activeStatus": true,
		"notes": "dictum augue malesuada",
		"company": "Nulla Semper Incorporated",
		"title": "Nam ac",
		"priority": "medium"
	},
	{
		"name": "Demetrius Walters",
		"contactFrequency": "None",
		"email": "Aliquam@sapienCrasdolor.org",
		"phone": "7364310712",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "Aliquam",
		"activeStatus": false,
		"notes": "semper, dui lectus rutrum urna, nec luctus felis purus",
		"company": "Mauris Id Associates",
		"title": "sit",
		"priority": "high"
	},
	{
		"name": "Erica Walls",
		"contactFrequency": "Monthly",
		"email": "pede@a.edu",
		"phone": "4381057521",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "rutrum",
		"activeStatus": false,
		"notes": "semper pretium neque. Morbi quis urna. Nunc quis arcu vel",
		"company": "Mi Duis Incorporated",
		"title": "massa",
		"priority": "low"
	},
	{
		"name": "Martin Harrison",
		"contactFrequency": "Yearly",
		"email": "dictum.sapien@auguemalesuada.com",
		"phone": "3107735214",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "tempus",
		"activeStatus": true,
		"notes": "purus, in molestie tortor nibh sit amet orci.",
		"company": "Phasellus Elit Inc.",
		"title": "Sed eu eros.",
		"priority": "medium"
	},
	{
		"name": "Elton Jefferson",
		"contactFrequency": "Custom",
		"email": "nulla.ante@temporaugue.com",
		"phone": "5488291343",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "ridiculus",
		"activeStatus": false,
		"notes": "pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci",
		"company": "Nec Foundation",
		"title": "in aliquet lobortis,",
		"priority": "medium"
	},
	{
		"name": "Cherokee Shepherd",
		"contactFrequency": "Custom",
		"email": "id.libero.Donec@et.co.uk",
		"phone": "7532026545",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "odio",
		"activeStatus": true,
		"notes": "ut quam vel sapien imperdiet ornare. In faucibus.",
		"company": "Praesent Eu LLP",
		"title": "vel, vulputate eu,",
		"priority": "high"
	},
	{
		"name": "Isadora Kirby",
		"contactFrequency": "Custom",
		"email": "pellentesque@ut.com",
		"phone": "3685345992",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Aenean",
		"activeStatus": true,
		"notes": "amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna",
		"company": "Iaculis Nec LLP",
		"title": "vel",
		"priority": "low"
	},
	{
		"name": "Addison Wood",
		"contactFrequency": "Weekly",
		"email": "eget.magna.Suspendisse@nibh.net",
		"phone": "9175404365",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "Quisque",
		"activeStatus": true,
		"notes": "Proin vel arcu eu odio tristique pharetra. Quisque",
		"company": "Vel Venenatis Vel Ltd",
		"title": "Nulla aliquet.",
		"priority": "medium"
	},
	{
		"name": "Evan Cotton",
		"contactFrequency": "Custom",
		"email": "eu.neque@Phasellus.co.uk",
		"phone": "9794567614",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "in",
		"activeStatus": false,
		"notes": "augue ut",
		"company": "Mauris Suspendisse Aliquet Associates",
		"title": "erat,",
		"priority": "medium"
	},
	{
		"name": "George Kennedy",
		"contactFrequency": "Quarterly",
		"email": "Etiam.bibendum@maurissapiencursus.co.uk",
		"phone": "4969850719",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Nam",
		"activeStatus": true,
		"notes": "libero.",
		"company": "Inceptos Hymenaeos LLP",
		"title": "lorem,",
		"priority": "low"
	},
	{
		"name": "Mohammad Wilkinson",
		"contactFrequency": "Monthly",
		"email": "Sed@elitEtiam.org",
		"phone": "7827640196",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "pede.",
		"activeStatus": true,
		"notes": "Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis",
		"company": "Massa Industries",
		"title": "Donec",
		"priority": "medium"
	},
	{
		"name": "Alfreda Daniels",
		"contactFrequency": "Weekly",
		"email": "lorem.semper.auctor@Vivamuseuismodurna.edu",
		"phone": "6930710548",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "et",
		"activeStatus": false,
		"notes": "leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam",
		"company": "Vitae Posuere Company",
		"title": "mollis",
		"priority": "high"
	},
	{
		"name": "Kirsten Christensen",
		"contactFrequency": "Biweekly",
		"email": "Nulla.tincidunt@Quisquefringillaeuismod.co.uk",
		"phone": "3619081563",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "enim,",
		"activeStatus": false,
		"notes": "neque venenatis lacus.",
		"company": "Facilisis Magna Limited",
		"title": "montes, nascetur ridiculus",
		"priority": "high"
	},
	{
		"name": "Wing Ramsey",
		"contactFrequency": "Custom",
		"email": "iaculis@nisl.edu",
		"phone": "1996755584",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "quis,",
		"activeStatus": false,
		"notes": "Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus.",
		"company": "Vel Arcu Eu LLP",
		"title": "vehicula et,",
		"priority": "low"
	},
	{
		"name": "Linda Rodgers",
		"contactFrequency": "Custom",
		"email": "amet.luctus@mattissemper.ca",
		"phone": "3243381598",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "eleifend.",
		"activeStatus": true,
		"notes": "risus. Donec nibh enim, gravida sit amet,",
		"company": "Et Inc.",
		"title": "mauris. Morbi",
		"priority": "high"
	},
	{
		"name": "Alisa Reynolds",
		"contactFrequency": "Custom",
		"email": "odio@ut.org",
		"phone": "4970682655",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Nunc",
		"activeStatus": true,
		"notes": "purus ac tellus.",
		"company": "Eget Nisi Dictum Ltd",
		"title": "posuere",
		"priority": "medium"
	},
	{
		"name": "Unity Mullins",
		"contactFrequency": "Yearly",
		"email": "ultricies.dignissim.lacus@Incondimentum.co.uk",
		"phone": "1955854576",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "rutrum",
		"activeStatus": true,
		"notes": "vehicula et, rutrum eu, ultrices sit amet, risus. Donec",
		"company": "Duis Incorporated",
		"title": "Cras lorem",
		"priority": "low"
	},
	{
		"name": "Jakeem Chambers",
		"contactFrequency": "Weekly",
		"email": "at.arcu.Vestibulum@dapibus.org",
		"phone": "9035596779",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "felis.",
		"activeStatus": false,
		"notes": "a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis",
		"company": "Vitae Foundation",
		"title": "urna",
		"priority": "medium"
	},
	{
		"name": "Nevada Wilkins",
		"contactFrequency": "Biannual",
		"email": "Vivamus.molestie.dapibus@disparturientmontes.ca",
		"phone": "8455982573",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "sit",
		"activeStatus": true,
		"notes": "ac, feugiat non, lobortis quis, pede. Suspendisse",
		"company": "Netus Et Ltd",
		"title": "tincidunt. Donec vitae",
		"priority": "high"
	},
	{
		"name": "Alma Bailey",
		"contactFrequency": "Weekly",
		"email": "Sed.molestie@aliquetPhasellus.co.uk",
		"phone": "4843899210",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "cursus",
		"activeStatus": false,
		"notes": "faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse",
		"company": "Ipsum Leo Elementum Limited",
		"title": "enim.",
		"priority": "low"
	},
	{
		"name": "Driscoll Jones",
		"contactFrequency": "Custom",
		"email": "ipsum@nullamagna.co.uk",
		"phone": "8648782043",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "metus",
		"activeStatus": false,
		"notes": "eleifend nec, malesuada ut,",
		"company": "Dui Institute",
		"title": "ac",
		"priority": "low"
	},
	{
		"name": "Paula Herman",
		"contactFrequency": "Yearly",
		"email": "risus.Donec.egestas@ipsumCurabiturconsequat.org",
		"phone": "1757510283",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "vehicula.",
		"activeStatus": false,
		"notes": "eros non enim commodo hendrerit. Donec porttitor",
		"company": "Elementum Incorporated",
		"title": "mauris.",
		"priority": "high"
	},
	{
		"name": "Kristen Kidd",
		"contactFrequency": "Weekly",
		"email": "elit.pede.malesuada@purussapiengravida.net",
		"phone": "7036310376",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "vulputate",
		"activeStatus": false,
		"notes": "convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse",
		"company": "Lobortis Limited",
		"title": "montes,",
		"priority": "low"
	},
	{
		"name": "Noble Murray",
		"contactFrequency": "Custom",
		"email": "at@augueacipsum.net",
		"phone": "6395550121",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "nisl.",
		"activeStatus": false,
		"notes": "tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper,",
		"company": "Consectetuer Limited",
		"title": "mollis vitae, posuere",
		"priority": "high"
	},
	{
		"name": "Macon Owen",
		"contactFrequency": "None",
		"email": "arcu@elitEtiam.net",
		"phone": "8297768702",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "Nulla",
		"activeStatus": false,
		"notes": "enim diam vel arcu. Curabitur ut odio vel est tempor",
		"company": "Arcu LLP",
		"title": "molestie sodales.",
		"priority": "high"
	},
	{
		"name": "Aline Pollard",
		"contactFrequency": "Monthly",
		"email": "semper.erat@arcuvelquam.net",
		"phone": "1007730758",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "imperdiet",
		"activeStatus": true,
		"notes": "tempus risus. Donec egestas. Duis ac arcu.",
		"company": "Tellus Nunc Lectus LLP",
		"title": "risus",
		"priority": "low"
	},
	{
		"name": "Zahir Wynn",
		"contactFrequency": "Monthly",
		"email": "consectetuer@semperduilectus.edu",
		"phone": "6468346202",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "habitant",
		"activeStatus": true,
		"notes": "tincidunt",
		"company": "Dictum Placerat Corporation",
		"title": "ultricies ornare,",
		"priority": "high"
	},
	{
		"name": "Darrel Collins",
		"contactFrequency": "Biweekly",
		"email": "lectus@massaMauris.org",
		"phone": "8446127910",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "pretium",
		"activeStatus": false,
		"notes": "ac orci. Ut semper pretium neque. Morbi quis urna.",
		"company": "Neque Limited",
		"title": "netus et",
		"priority": "low"
	},
	{
		"name": "Amity Alvarado",
		"contactFrequency": "Quarterly",
		"email": "Nulla@odio.co.uk",
		"phone": "6595906992",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "Nam",
		"activeStatus": false,
		"notes": "consectetuer adipiscing elit. Aliquam auctor,",
		"company": "Quis Pede Suspendisse LLP",
		"title": "dui.",
		"priority": "low"
	},
	{
		"name": "Carolyn David",
		"contactFrequency": "Biannual",
		"email": "non.vestibulum.nec@luctuslobortisClass.org",
		"phone": "1088621927",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "purus",
		"activeStatus": false,
		"notes": "Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla",
		"company": "Vulputate Velit Limited",
		"title": "amet",
		"priority": "high"
	},
	{
		"name": "Jescie Joyner",
		"contactFrequency": "Quarterly",
		"email": "fringilla.ornare.placerat@purusin.org",
		"phone": "7580542676",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "pellentesque.",
		"activeStatus": false,
		"notes": "lorem. Donec elementum, lorem ut aliquam iaculis,",
		"company": "Suspendisse Associates",
		"title": "semper rutrum. Fusce",
		"priority": "low"
	},
	{
		"name": "Sigourney Sellers",
		"contactFrequency": "Monthly",
		"email": "amet@odioauctorvitae.co.uk",
		"phone": "3017454172",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "turpis",
		"activeStatus": false,
		"notes": "ad",
		"company": "Cras Dictum Consulting",
		"title": "tristique ac, eleifend",
		"priority": "high"
	},
	{
		"name": "Edan Rivers",
		"contactFrequency": "None",
		"email": "Nunc@ante.ca",
		"phone": "6278429964",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "varius",
		"activeStatus": false,
		"notes": "congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus",
		"company": "Phasellus Ltd",
		"title": "eu nibh vulputate",
		"priority": "high"
	},
	{
		"name": "Ryder Rosales",
		"contactFrequency": "Yearly",
		"email": "ligula.Aenean.euismod@musDonecdignissim.co.uk",
		"phone": "8432888841",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "ultricies",
		"activeStatus": false,
		"notes": "dis parturient montes, nascetur ridiculus mus.",
		"company": "Vestibulum Ante PC",
		"title": "a",
		"priority": "medium"
	},
	{
		"name": "Uriah Black",
		"contactFrequency": "Quarterly",
		"email": "at@nec.net",
		"phone": "2377439409",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "amet",
		"activeStatus": true,
		"notes": "lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque",
		"company": "Est Congue A Consulting",
		"title": "enim mi",
		"priority": "high"
	},
	{
		"name": "Tyrone Reid",
		"contactFrequency": "Quarterly",
		"email": "metus@eueratsemper.co.uk",
		"phone": "2232989369",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "pede",
		"activeStatus": true,
		"notes": "cursus vestibulum. Mauris magna. Duis dignissim",
		"company": "Auctor Mauris Vel Incorporated",
		"title": "sagittis augue, eu",
		"priority": "low"
	},
	{
		"name": "Yoshio Coleman",
		"contactFrequency": "Weekly",
		"email": "gravida.Aliquam@luctus.org",
		"phone": "3954023899",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "tempor,",
		"activeStatus": true,
		"notes": "In condimentum. Donec at arcu. Vestibulum ante",
		"company": "Ligula Aenean Corp.",
		"title": "a purus.",
		"priority": "medium"
	},
	{
		"name": "Gabriel Aguirre",
		"contactFrequency": "Yearly",
		"email": "metus@Integersem.ca",
		"phone": "5649985216",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "dolor",
		"activeStatus": true,
		"notes": "magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante.",
		"company": "Vehicula Pellentesque Tincidunt Industries",
		"title": "nisi",
		"priority": "high"
	},
	{
		"name": "Grant Ashley",
		"contactFrequency": "Monthly",
		"email": "viverra.Maecenas@anteNuncmauris.org",
		"phone": "8231572653",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "id,",
		"activeStatus": false,
		"notes": "quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos",
		"company": "Mauris Magna Duis LLP",
		"title": "ac arcu. Nunc",
		"priority": "low"
	},
	{
		"name": "Galena Knapp",
		"contactFrequency": "Weekly",
		"email": "enim@ametorciUt.net",
		"phone": "8473453001",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "enim",
		"activeStatus": false,
		"notes": "ac orci. Ut semper pretium neque. Morbi quis urna.",
		"company": "Odio Semper Cursus PC",
		"title": "vehicula aliquet libero.",
		"priority": "low"
	},
	{
		"name": "Britanni Schmidt",
		"contactFrequency": "Biweekly",
		"email": "lectus@pharetrasedhendrerit.com",
		"phone": "1904634665",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "Nullam",
		"activeStatus": true,
		"notes": "congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,",
		"company": "Vulputate Risus A Foundation",
		"title": "vulputate",
		"priority": "high"
	},
	{
		"name": "Echo Justice",
		"contactFrequency": "Monthly",
		"email": "nonummy.ac@morbi.edu",
		"phone": "4493524929",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "tincidunt",
		"activeStatus": true,
		"notes": "massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor",
		"company": "Nibh Vulputate Institute",
		"title": "conubia nostra, per",
		"priority": "high"
	},
	{
		"name": "Jessamine Hancock",
		"contactFrequency": "Quarterly",
		"email": "eu.dui@libero.com",
		"phone": "7463811923",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Sed",
		"activeStatus": true,
		"notes": "dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus",
		"company": "Et Ultrices LLP",
		"title": "ipsum leo",
		"priority": "low"
	},
	{
		"name": "Uma Roberson",
		"contactFrequency": "Yearly",
		"email": "Quisque@habitantmorbitristique.net",
		"phone": "8622901412",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "et,",
		"activeStatus": true,
		"notes": "pede, malesuada vel, venenatis vel, faucibus",
		"company": "Cras PC",
		"title": "at,",
		"priority": "low"
	},
	{
		"name": "Leslie Gamble",
		"contactFrequency": "Weekly",
		"email": "lectus.justo.eu@risusDuisa.co.uk",
		"phone": "9548162557",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "mauris",
		"activeStatus": false,
		"notes": "interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt",
		"company": "Congue Incorporated",
		"title": "lorem tristique aliquet.",
		"priority": "high"
	},
	{
		"name": "Berk Grimes",
		"contactFrequency": "Yearly",
		"email": "feugiat.nec.diam@tinciduntneque.ca",
		"phone": "1379150439",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "imperdiet",
		"activeStatus": false,
		"notes": "libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris",
		"company": "Lobortis LLC",
		"title": "tempor erat neque",
		"priority": "medium"
	},
	{
		"name": "Ivory Bolton",
		"contactFrequency": "Yearly",
		"email": "vel.pede@Namnulla.com",
		"phone": "1115474878",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "Cum",
		"activeStatus": false,
		"notes": "ornare, elit elit fermentum risus, at fringilla purus mauris a",
		"company": "Vitae Incorporated",
		"title": "vitae diam.",
		"priority": "low"
	},
	{
		"name": "Meredith Aguirre",
		"contactFrequency": "Biweekly",
		"email": "lectus.ante.dictum@ultriciesornareelit.co.uk",
		"phone": "9498495698",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "in",
		"activeStatus": true,
		"notes": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
		"company": "Quam Foundation",
		"title": "non lorem",
		"priority": "high"
	},
	{
		"name": "Stewart Keller",
		"contactFrequency": "None",
		"email": "Aliquam.fringilla.cursus@egestasDuisac.edu",
		"phone": "8762292770",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "vitae",
		"activeStatus": false,
		"notes": "sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie",
		"company": "Lacus Quisque Foundation",
		"title": "scelerisque",
		"priority": "medium"
	},
	{
		"name": "Rinah Odom",
		"contactFrequency": "Yearly",
		"email": "tristique.senectus.et@mieleifend.org",
		"phone": "2243276460",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Fusce",
		"activeStatus": false,
		"notes": "Cum sociis natoque penatibus et magnis",
		"company": "Tincidunt Donec Vitae Incorporated",
		"title": "metus",
		"priority": "medium"
	},
	{
		"name": "Patience Cervantes",
		"contactFrequency": "Quarterly",
		"email": "dolor.nonummy.ac@idenim.ca",
		"phone": "2851132714",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "arcu.",
		"activeStatus": true,
		"notes": "sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer",
		"company": "Faucibus Id Company",
		"title": "elit, a",
		"priority": "high"
	},
	{
		"name": "Hanae Rios",
		"contactFrequency": "Quarterly",
		"email": "Sed@Suspendisse.org",
		"phone": "1211469790",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "erat",
		"activeStatus": false,
		"notes": "nunc ac mattis ornare, lectus ante",
		"company": "Vitae Dolor LLC",
		"title": "suscipit",
		"priority": "medium"
	},
	{
		"name": "Howard Mayer",
		"contactFrequency": "Custom",
		"email": "arcu.eu@blanditNamnulla.co.uk",
		"phone": "6176953878",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "magna.",
		"activeStatus": false,
		"notes": "metus.",
		"company": "Suspendisse Ac Metus Corp.",
		"title": "erat vitae",
		"priority": "low"
	},
	{
		"name": "Ariana Fleming",
		"contactFrequency": "None",
		"email": "eu@apurusDuis.org",
		"phone": "7034576434",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "interdum.",
		"activeStatus": false,
		"notes": "Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim",
		"company": "Lorem Ipsum Dolor PC",
		"title": "luctus felis",
		"priority": "medium"
	},
	{
		"name": "Darrel Walls",
		"contactFrequency": "Yearly",
		"email": "et.magnis@elementum.edu",
		"phone": "1940259958",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "luctus",
		"activeStatus": true,
		"notes": "lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel",
		"company": "Lorem Ipsum Industries",
		"title": "magna tellus faucibus",
		"priority": "low"
	},
	{
		"name": "Rajah Baird",
		"contactFrequency": "Weekly",
		"email": "metus.eu@ultrices.net",
		"phone": "1881896475",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "amet,",
		"activeStatus": false,
		"notes": "morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
		"company": "Cras Consulting",
		"title": "placerat.",
		"priority": "low"
	},
	{
		"name": "Beck Gallagher",
		"contactFrequency": "Monthly",
		"email": "elit.Etiam.laoreet@Maurisquisturpis.com",
		"phone": "1731670820",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Fusce",
		"activeStatus": false,
		"notes": "ornare, libero",
		"company": "Amet Risus Donec Associates",
		"title": "eget",
		"priority": "high"
	},
	{
		"name": "Caldwell Jones",
		"contactFrequency": "Biweekly",
		"email": "mauris.Morbi@necquamCurabitur.net",
		"phone": "8392451720",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "sem",
		"activeStatus": false,
		"notes": "eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat",
		"company": "Convallis PC",
		"title": "convallis convallis dolor.",
		"priority": "medium"
	},
	{
		"name": "Malcolm Ewing",
		"contactFrequency": "Weekly",
		"email": "blandit@Aliquameratvolutpat.net",
		"phone": "8533926843",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "nulla",
		"activeStatus": true,
		"notes": "dapibus rutrum, justo. Praesent",
		"company": "Eros Non LLC",
		"title": "sit amet,",
		"priority": "medium"
	},
	{
		"name": "Rose Sanders",
		"contactFrequency": "Quarterly",
		"email": "vestibulum.lorem@gravidaPraesenteu.com",
		"phone": "5721635444",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "massa",
		"activeStatus": false,
		"notes": "eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit",
		"company": "Mi Tempor LLP",
		"title": "eget",
		"priority": "low"
	},
	{
		"name": "Sopoline Gregory",
		"contactFrequency": "Monthly",
		"email": "Cras@Sed.net",
		"phone": "2630510850",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "luctus,",
		"activeStatus": false,
		"notes": "ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis",
		"company": "Libero LLP",
		"title": "egestas.",
		"priority": "low"
	},
	{
		"name": "Naida Crosby",
		"contactFrequency": "Quarterly",
		"email": "convallis.dolor@Phasellusfermentum.co.uk",
		"phone": "8036795088",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "purus.",
		"activeStatus": true,
		"notes": "pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis",
		"company": "Urna Corporation",
		"title": "nisi. Mauris nulla.",
		"priority": "medium"
	},
	{
		"name": "Guy Wagner",
		"contactFrequency": "Yearly",
		"email": "magna.a.neque@acfermentumvel.edu",
		"phone": "2094720155",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "natoque",
		"activeStatus": true,
		"notes": "magnis dis parturient montes, nascetur ridiculus mus. Aenean eget",
		"company": "Fringilla Cursus LLP",
		"title": "tincidunt vehicula",
		"priority": "high"
	},
	{
		"name": "Thomas Rosa",
		"contactFrequency": "Biweekly",
		"email": "molestie@Donecest.org",
		"phone": "8358495814",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "nec",
		"activeStatus": true,
		"notes": "rutrum. Fusce dolor quam, elementum at, egestas",
		"company": "Est Tempor Company",
		"title": "a, enim. Suspendisse",
		"priority": "low"
	},
	{
		"name": "Sydney Hines",
		"contactFrequency": "Custom",
		"email": "diam.lorem.auctor@eunibh.edu",
		"phone": "6635710697",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "eu",
		"activeStatus": true,
		"notes": "ipsum",
		"company": "Nullam Enim Company",
		"title": "et, eros.",
		"priority": "medium"
	},
	{
		"name": "Zeph Lucas",
		"contactFrequency": "Quarterly",
		"email": "tempus@lacusMaurisnon.edu",
		"phone": "4538314401",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "aliquet",
		"activeStatus": true,
		"notes": "nulla vulputate dui, nec tempus mauris erat eget ipsum.",
		"company": "Mollis Vitae Posuere PC",
		"title": "Sed diam",
		"priority": "low"
	},
	{
		"name": "Brock Stanton",
		"contactFrequency": "Quarterly",
		"email": "cursus.Nunc.mauris@Sed.com",
		"phone": "5900228771",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "Suspendisse",
		"activeStatus": true,
		"notes": "nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper",
		"company": "Ipsum Company",
		"title": "tempus eu,",
		"priority": "medium"
	},
	{
		"name": "Deborah Slater",
		"contactFrequency": "Biweekly",
		"email": "facilisis.facilisis.magna@eget.net",
		"phone": "3223970687",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Sed",
		"activeStatus": false,
		"notes": "odio vel est tempor bibendum. Donec felis orci,",
		"company": "Sollicitudin Orci Sem LLP",
		"title": "lobortis ultrices.",
		"priority": "medium"
	},
	{
		"name": "Chelsea Fulton",
		"contactFrequency": "Biweekly",
		"email": "tortor.Integer.aliquam@Nuncmauriselit.co.uk",
		"phone": "3983686687",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "sit",
		"activeStatus": false,
		"notes": "morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a",
		"company": "Nisi A Odio Incorporated",
		"title": "ipsum sodales",
		"priority": "medium"
	},
	{
		"name": "Jonas Fleming",
		"contactFrequency": "Yearly",
		"email": "pharetra@Curabitursed.net",
		"phone": "4135724341",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "vehicula.",
		"activeStatus": false,
		"notes": "a odio semper cursus.",
		"company": "Augue Ac Foundation",
		"title": "sit",
		"priority": "medium"
	},
	{
		"name": "Gary Farley",
		"contactFrequency": "Weekly",
		"email": "tempus.eu.ligula@vulputatemaurissagittis.org",
		"phone": "1276247314",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "lectus",
		"activeStatus": false,
		"notes": "enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum",
		"company": "Eu Inc.",
		"title": "vel, venenatis vel,",
		"priority": "medium"
	},
	{
		"name": "Joelle Jordan",
		"contactFrequency": "Quarterly",
		"email": "at@posuereat.ca",
		"phone": "4215745623",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "vel",
		"activeStatus": false,
		"notes": "eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed,",
		"company": "Auctor Nunc Nulla Incorporated",
		"title": "neque venenatis lacus.",
		"priority": "low"
	},
	{
		"name": "Christopher Burnett",
		"contactFrequency": "Quarterly",
		"email": "posuere@inaliquet.net",
		"phone": "8579936399",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "metus.",
		"activeStatus": true,
		"notes": "Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla",
		"company": "Quis Arcu Vel Corp.",
		"title": "id",
		"priority": "medium"
	},
	{
		"name": "Kelly Watts",
		"contactFrequency": "Yearly",
		"email": "in.felis@Inmipede.edu",
		"phone": "3803964998",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "at",
		"activeStatus": false,
		"notes": "rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam",
		"company": "Orci Corp.",
		"title": "urna",
		"priority": "low"
	},
	{
		"name": "Hu Cherry",
		"contactFrequency": "Quarterly",
		"email": "sit.amet.diam@libero.org",
		"phone": "6807807517",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "ipsum",
		"activeStatus": true,
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus",
		"company": "Amet Industries",
		"title": "neque pellentesque",
		"priority": "low"
	},
	{
		"name": "Francesca Britt",
		"contactFrequency": "Custom",
		"email": "Duis@erat.co.uk",
		"phone": "9967014268",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "Suspendisse",
		"activeStatus": false,
		"notes": "interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis",
		"company": "Magna Duis Dignissim Limited",
		"title": "libero. Proin mi.",
		"priority": "high"
	},
	{
		"name": "Thaddeus Chang",
		"contactFrequency": "Yearly",
		"email": "lectus.pede@Phasellusdolorelit.com",
		"phone": "1704582104",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "cubilia",
		"activeStatus": true,
		"notes": "Curabitur vel lectus. Cum",
		"company": "Suspendisse Dui Limited",
		"title": "Cras",
		"priority": "high"
	},
	{
		"name": "Karina Whitaker",
		"contactFrequency": "Quarterly",
		"email": "eget.odio.Aliquam@interdumSed.net",
		"phone": "8264968790",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "gravida",
		"activeStatus": true,
		"notes": "vel,",
		"company": "Ultrices Posuere Corp.",
		"title": "ipsum. Suspendisse non",
		"priority": "high"
	},
	{
		"name": "Chelsea Torres",
		"contactFrequency": "Custom",
		"email": "libero.et@liberonecligula.org",
		"phone": "9441358676",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "In",
		"activeStatus": false,
		"notes": "vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit",
		"company": "Diam Sed Foundation",
		"title": "Nullam feugiat",
		"priority": "high"
	},
	{
		"name": "Justina Shannon",
		"contactFrequency": "Quarterly",
		"email": "diam@ametconsectetueradipiscing.com",
		"phone": "1984076783",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "consectetuer,",
		"activeStatus": true,
		"notes": "scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero",
		"company": "A Feugiat LLC",
		"title": "ullamcorper eu,",
		"priority": "low"
	},
	{
		"name": "Dahlia Swanson",
		"contactFrequency": "Monthly",
		"email": "scelerisque.neque@diamlorem.edu",
		"phone": "5531111656",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "intimate",
		"contextSpace": "id,",
		"activeStatus": false,
		"notes": "Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc",
		"company": "Vestibulum Ltd",
		"title": "egestas ligula. Nullam",
		"priority": "high"
	},
	{
		"name": "Guy Burt",
		"contactFrequency": "None",
		"email": "a@lorem.com",
		"phone": "9447274912",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "mauris",
		"activeStatus": true,
		"notes": "Cras eu tellus eu augue porttitor",
		"company": "Nisl Nulla Eu PC",
		"title": "Suspendisse",
		"priority": "high"
	},
	{
		"name": "Winter Mendez",
		"contactFrequency": "Biweekly",
		"email": "nostra.per@estmollis.com",
		"phone": "4831068331",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "massa.",
		"activeStatus": false,
		"notes": "morbi tristique senectus et netus et malesuada fames ac",
		"company": "Feugiat Institute",
		"title": "Proin mi.",
		"priority": "medium"
	},
	{
		"name": "Warren Jefferson",
		"contactFrequency": "Biannual",
		"email": "neque.vitae.semper@neque.ca",
		"phone": "6642775872",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "tortor.",
		"activeStatus": true,
		"notes": "mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor",
		"company": "Primis In LLC",
		"title": "felis. Nulla",
		"priority": "high"
	},
	{
		"name": "Rahim Sheppard",
		"contactFrequency": "Quarterly",
		"email": "posuere@dolorsit.co.uk",
		"phone": "1039561093",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "In",
		"activeStatus": true,
		"notes": "tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu,",
		"company": "Facilisis Inc.",
		"title": "non, lobortis",
		"priority": "high"
	},
	{
		"name": "Cairo Houston",
		"contactFrequency": "Quarterly",
		"email": "quis.accumsan@sit.org",
		"phone": "9699534311",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "ac",
		"activeStatus": true,
		"notes": "a tortor.",
		"company": "Duis Gravida Praesent Foundation",
		"title": "eu nibh",
		"priority": "medium"
	},
	{
		"name": "Patrick Buck",
		"contactFrequency": "Monthly",
		"email": "lectus.pede.ultrices@Proinsed.com",
		"phone": "6178879572",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "sit",
		"activeStatus": false,
		"notes": "Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat.",
		"company": "Ornare Sagittis Corporation",
		"title": "luctus sit",
		"priority": "low"
	},
	{
		"name": "Lydia Jacobs",
		"contactFrequency": "None",
		"email": "ac@nondapibusrutrum.org",
		"phone": "2651942858",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "rutrum.",
		"activeStatus": false,
		"notes": "non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc",
		"company": "Sed Pharetra Consulting",
		"title": "eget, volutpat",
		"priority": "high"
	},
	{
		"name": "Ariana Bowers",
		"contactFrequency": "Biweekly",
		"email": "erat.volutpat@intempus.net",
		"phone": "7932003317",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "nulla.",
		"activeStatus": false,
		"notes": "imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus.",
		"company": "Dolor Quam Elementum Industries",
		"title": "lectus pede",
		"priority": "high"
	},
	{
		"name": "Holly Mack",
		"contactFrequency": "Custom",
		"email": "convallis.erat.eget@milacinia.net",
		"phone": "2010551664",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Donec",
		"activeStatus": false,
		"notes": "dui, nec",
		"company": "Amet Risus Donec Consulting",
		"title": "ante, iaculis",
		"priority": "high"
	},
	{
		"name": "Patience Sheppard",
		"contactFrequency": "Quarterly",
		"email": "vel.nisl.Quisque@lacusMauris.com",
		"phone": "5337065072",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "varius",
		"activeStatus": true,
		"notes": "odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non",
		"company": "Amet Company",
		"title": "Cum sociis natoque",
		"priority": "medium"
	},
	{
		"name": "Janna Mercer",
		"contactFrequency": "Yearly",
		"email": "neque.venenatis@tristiquepharetra.edu",
		"phone": "6343657577",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "familiar",
		"contextSpace": "nec",
		"activeStatus": false,
		"notes": "a tortor. Nunc",
		"company": "Eget Varius Ultrices LLP",
		"title": "Cum sociis natoque",
		"priority": "medium"
	},
	{
		"name": "Joelle Reilly",
		"contactFrequency": "Biannual",
		"email": "Maecenas@at.com",
		"phone": "3590157755",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "meaningful",
		"contextSpace": "Lorem",
		"activeStatus": true,
		"notes": "enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies",
		"company": "Sem LLC",
		"title": "pede,",
		"priority": "high"
	},
	{
		"name": "Felicia Holman",
		"contactFrequency": "Weekly",
		"email": "mattis.Cras@quis.edu",
		"phone": "8416504929",
		"LinkedIn": "https://www.linkedin.com/",
		"familiarity": "unfamiliar",
		"contextSpace": "odio",
		"activeStatus": true,
		"notes": "adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl",
		"company": "Donec Foundation",
		"title": "sociis",
		"priority": "low"
	}
]


/////  SCRIPT  //////

function randomDate(start, end) {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))
}


const initialCount = db.contacts.count();

for (let i = 0; i < 100; i += 1) {

  const id = initialCount + i + 1;
  const name = mockData[i].name;
  const contactFrequency = mockData[i].contactFrequency;
  const email = mockData[i].email;
  const phone = mockData[i].phone;
  const LinkedIn = mockData[i].LinkedIn + name;
  const priority = mockData[i].priority;
  const familiarity = mockData[i].familiarity;
  const contextSpace = mockData[i].contextSpace;
  const activeStatus = mockData[i].activeStatus;
  // Generate date between 2001 and present
  const lastContactDate = randomDate(new Date(2001, 0, 1), new Date());
  const notes = mockData[i].notes;
  const company = mockData[i].company;
  // Generate date between today and 2 years from today
  const nextContactDate = randomDate(new Date(), new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 730));
  const title = mockData[i].title + `${i}`;

  const contact = {
    id, 
    name, 
    contactFrequency, 
    email, 
    phone, 
    LinkedIn, 
    priority,
    familiarity,
    contextSpace,
    activeStatus,
    lastContactDate,
    notes,
    company,
    nextContactDate,
    title,
  };

  db.contacts.insertOne(contact);
}

const count = db.contacts.count();
db.counters.update({ _id: 'contacts' }, { $set: { current: count } });

print('New contacts count:', count);
