////https://www.generatedata.com/


export let mockData =[
	{
		"name": "Martina Landry",
		"contactFrequency": "Yearly",
		"email": "senectus.et@fringillami.com",
		"phone": "1-357-936-4021",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "ultrices.",
		"activeStatus": true,
		"lastContactDate": "2020-08-25T16:54:43-07:00",
		"notes": "Lorem",
		"company": "Phasellus Fermentum Ltd",
		"nextContactDate": "2021-03-25T17:07:28-07:00",
		"title": "dui"
	},
	{
		"name": "Emery Crane",
		"contactFrequency": "Weekly",
		"email": "rhoncus@Vivamusmolestie.ca",
		"phone": "1-336-463-1627",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "sit",
		"activeStatus": false,
		"lastContactDate": "2020-11-15T12:56:00-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Et Corp.",
		"nextContactDate": "2020-12-20T10:53:43-08:00",
		"title": "at risus."
	},
	{
		"name": "Nicholas Q. Gonzalez",
		"contactFrequency": "None",
		"email": "blandit.Nam@euerat.edu",
		"phone": "1-555-493-9782",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "tempus",
		"activeStatus": true,
		"lastContactDate": "2021-02-06T17:14:44-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Mauris Limited",
		"nextContactDate": "2020-09-30T01:54:16-07:00",
		"title": "lacinia."
	},
	{
		"name": "Amy E. Myers",
		"contactFrequency": "Monthly",
		"email": "Phasellus.elit.pede@sitamet.org",
		"phone": "1-370-671-1718",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "egestas",
		"activeStatus": false,
		"lastContactDate": "2021-04-13T09:07:53-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Nunc Sollicitudin Company",
		"nextContactDate": "2020-12-28T12:10:49-08:00",
		"title": "Aliquam tincidunt,"
	},
	{
		"name": "Peter Barnes",
		"contactFrequency": "Monthly",
		"email": "arcu.Vivamus@erat.org",
		"phone": "1-922-899-4732",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "ac",
		"activeStatus": true,
		"lastContactDate": "2021-03-19T01:14:25-07:00",
		"notes": "Lorem ipsum dolor",
		"company": "Amet Ultricies Industries",
		"nextContactDate": "2021-01-09T14:27:02-08:00",
		"title": "lorem ut aliquam"
	},
	{
		"name": "Indigo F. Mueller",
		"contactFrequency": "None",
		"email": "Nullam.enim.Sed@ultricesVivamus.co.uk",
		"phone": "1-722-736-6515",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "dictum",
		"activeStatus": false,
		"lastContactDate": "2021-05-18T12:50:22-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Nec Consulting",
		"nextContactDate": "2021-02-21T13:28:22-08:00",
		"title": "massa. Integer vitae"
	},
	{
		"name": "Emerson U. Vasquez",
		"contactFrequency": "BiWeekly",
		"email": "odio@tortorNunc.edu",
		"phone": "1-220-336-5152",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "ipsum.",
		"activeStatus": true,
		"lastContactDate": "2020-12-31T14:23:34-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Quam A Associates",
		"nextContactDate": "2021-06-04T21:07:40-07:00",
		"title": "id magna et"
	},
	{
		"name": "Abbot X. Oliver",
		"contactFrequency": "Yearly",
		"email": "lacus.Nulla.tincidunt@tellusidnunc.com",
		"phone": "1-620-551-2067",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "Vestibulum",
		"activeStatus": false,
		"lastContactDate": "2021-01-11T14:32:53-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Proin Sed Turpis Associates",
		"nextContactDate": "2020-11-06T21:11:31-08:00",
		"title": "scelerisque dui."
	},
	{
		"name": "Nomlanga Fowler",
		"contactFrequency": "None",
		"email": "faucibus.orci@et.net",
		"phone": "1-311-683-8727",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "Pellentesque",
		"activeStatus": true,
		"lastContactDate": "2020-12-18T10:21:28-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Pharetra Quisque Institute",
		"nextContactDate": "2020-10-28T02:45:46-07:00",
		"title": "ipsum dolor sit"
	},
	{
		"name": "Shea Herring",
		"contactFrequency": "BiWeekly",
		"email": "ipsum.nunc@ridiculus.ca",
		"phone": "1-360-997-0158",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "aliquet",
		"activeStatus": false,
		"lastContactDate": "2020-11-29T13:04:03-08:00",
		"notes": "Lorem ipsum dolor sit",
		"company": "Cursus Luctus Ipsum Limited",
		"nextContactDate": "2021-05-04T14:08:10-07:00",
		"title": "pulvinar"
	},
	{
		"name": "Leonard Morin",
		"contactFrequency": "Biannual",
		"email": "ut.pharetra.sed@utmolestiein.com",
		"phone": "1-307-974-1000",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "taciti",
		"activeStatus": false,
		"lastContactDate": "2020-09-03T11:45:14-07:00",
		"notes": "Lorem ipsum dolor",
		"company": "A Inc.",
		"nextContactDate": "2020-11-05T23:20:37-08:00",
		"title": "consectetuer"
	},
	{
		"name": "Summer V. Robinson",
		"contactFrequency": "None",
		"email": "Duis.risus.odio@sedliberoProin.ca",
		"phone": "1-422-334-5338",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "Fusce",
		"activeStatus": true,
		"lastContactDate": "2021-06-07T06:45:04-07:00",
		"notes": "Lorem ipsum dolor sit",
		"company": "Gravida Consulting",
		"nextContactDate": "2021-07-12T10:33:58-07:00",
		"title": "magnis dis"
	},
	{
		"name": "Vielka F. Fletcher",
		"contactFrequency": "None",
		"email": "pede@gravidaAliquamtincidunt.co.uk",
		"phone": "1-336-740-0861",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "amet",
		"activeStatus": false,
		"lastContactDate": "2020-09-10T07:48:32-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Dictum Sapien PC",
		"nextContactDate": "2021-06-11T13:07:33-07:00",
		"title": "Sed molestie. Sed"
	},
	{
		"name": "Hop Monroe",
		"contactFrequency": "BiWeekly",
		"email": "feugiat.metus@arcuVestibulumut.co.uk",
		"phone": "1-397-853-6968",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "bibendum",
		"activeStatus": true,
		"lastContactDate": "2020-11-09T00:27:08-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Non Sollicitudin A PC",
		"nextContactDate": "2021-02-15T17:59:16-08:00",
		"title": "ridiculus mus."
	},
	{
		"name": "Josephine J. Trevino",
		"contactFrequency": "Weekly",
		"email": "ullamcorper@vestibulumnequesed.co.uk",
		"phone": "1-411-828-4056",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "massa",
		"activeStatus": false,
		"lastContactDate": "2020-12-27T03:05:21-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
		"company": "Etiam Imperdiet LLP",
		"nextContactDate": "2021-05-08T21:19:28-07:00",
		"title": "nec urna et"
	},
	{
		"name": "Faith P. Barlow",
		"contactFrequency": "None",
		"email": "nostra.per@atvelit.co.uk",
		"phone": "1-758-305-4927",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "est.",
		"activeStatus": true,
		"lastContactDate": "2021-06-18T21:00:16-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "In Company",
		"nextContactDate": "2020-11-09T08:15:24-08:00",
		"title": "dapibus"
	},
	{
		"name": "Rama P. Brock",
		"contactFrequency": "Monthly",
		"email": "gravida.Aliquam@mollisIntegertincidunt.org",
		"phone": "1-180-708-3861",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "egestas",
		"activeStatus": true,
		"lastContactDate": "2021-03-08T23:16:56-08:00",
		"notes": "Lorem",
		"company": "Volutpat Ltd",
		"nextContactDate": "2021-07-06T03:09:18-07:00",
		"title": "amet luctus"
	},
	{
		"name": "Rashad Odom",
		"contactFrequency": "None",
		"email": "sapien.gravida.non@acfacilisis.co.uk",
		"phone": "1-727-825-8952",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "ut,",
		"activeStatus": true,
		"lastContactDate": "2021-01-26T10:28:43-08:00",
		"notes": "Lorem",
		"company": "Aliquet Inc.",
		"nextContactDate": "2021-01-11T11:44:44-08:00",
		"title": "fames ac turpis"
	},
	{
		"name": "Sharon Christian",
		"contactFrequency": "Monthly",
		"email": "Aliquam@nonummy.ca",
		"phone": "1-212-166-6135",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "Quisque",
		"activeStatus": true,
		"lastContactDate": "2020-11-28T23:15:00-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Arcu Vestibulum Ante Inc.",
		"nextContactDate": "2020-09-04T13:01:44-07:00",
		"title": "velit egestas"
	},
	{
		"name": "Nita L. Davidson",
		"contactFrequency": "Quarterly",
		"email": "facilisi@vitaevelitegestas.org",
		"phone": "1-885-997-8652",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "nonummy",
		"activeStatus": false,
		"lastContactDate": "2021-02-17T12:34:36-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Dictum Eleifend Limited",
		"nextContactDate": "2021-06-09T17:27:06-07:00",
		"title": "Sed eu nibh"
	},
	{
		"name": "Seth Beck",
		"contactFrequency": "Monthly",
		"email": "In.at.pede@SednequeSed.co.uk",
		"phone": "1-475-146-9884",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "odio",
		"activeStatus": false,
		"lastContactDate": "2020-08-14T15:35:25-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Integer Sem Elit Corporation",
		"nextContactDate": "2020-09-26T19:44:10-07:00",
		"title": "Cras"
	},
	{
		"name": "Adrienne D. Haney",
		"contactFrequency": "BiWeekly",
		"email": "nibh@acipsum.edu",
		"phone": "1-646-328-2188",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "libero",
		"activeStatus": true,
		"lastContactDate": "2020-11-22T23:09:59-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Proin Sed Turpis Ltd",
		"nextContactDate": "2021-01-17T21:54:43-08:00",
		"title": "erat. Etiam"
	},
	{
		"name": "Lyle Branch",
		"contactFrequency": "None",
		"email": "molestie@parturientmontesnascetur.ca",
		"phone": "1-119-284-9157",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "feugiat",
		"activeStatus": true,
		"lastContactDate": "2021-05-19T00:52:23-07:00",
		"notes": "Lorem ipsum dolor sit",
		"company": "Pellentesque Corporation",
		"nextContactDate": "2021-06-10T16:18:44-07:00",
		"title": "ante blandit viverra."
	},
	{
		"name": "Ralph E. Christian",
		"contactFrequency": "BiWeekly",
		"email": "a@nisl.com",
		"phone": "1-368-839-7395",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "est",
		"activeStatus": false,
		"lastContactDate": "2020-10-05T03:34:37-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Non Consulting",
		"nextContactDate": "2020-12-31T00:57:45-08:00",
		"title": "Vivamus nibh dolor,"
	},
	{
		"name": "Abigail O. Garza",
		"contactFrequency": "None",
		"email": "vel.nisl@seddui.edu",
		"phone": "1-726-849-4219",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "cursus.",
		"activeStatus": true,
		"lastContactDate": "2020-08-03T08:34:13-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Nibh Enim Associates",
		"nextContactDate": "2021-04-10T09:30:18-07:00",
		"title": "erat. Etiam"
	},
	{
		"name": "Roanna N. Moore",
		"contactFrequency": "Quarterly",
		"email": "mauris.a@ornare.net",
		"phone": "1-117-230-8587",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "quis,",
		"activeStatus": false,
		"lastContactDate": "2021-02-18T10:53:23-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Accumsan LLC",
		"nextContactDate": "2020-11-09T15:31:59-08:00",
		"title": "molestie in, tempus"
	},
	{
		"name": "Emi C. Stokes",
		"contactFrequency": "Weekly",
		"email": "risus.Donec.egestas@pellentesqueSeddictum.net",
		"phone": "1-733-272-1787",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "risus.",
		"activeStatus": true,
		"lastContactDate": "2021-02-02T05:30:00-08:00",
		"notes": "Lorem ipsum dolor sit",
		"company": "Quam LLC",
		"nextContactDate": "2020-12-22T13:49:38-08:00",
		"title": "lorem semper auctor."
	},
	{
		"name": "Amena B. Stephenson",
		"contactFrequency": "Quarterly",
		"email": "risus@ac.ca",
		"phone": "1-322-619-2133",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "conubia",
		"activeStatus": true,
		"lastContactDate": "2020-10-28T00:56:56-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "A Sollicitudin Orci Industries",
		"nextContactDate": "2020-12-05T21:22:27-08:00",
		"title": "imperdiet dictum"
	},
	{
		"name": "Eagan C. Mcclain",
		"contactFrequency": "Quarterly",
		"email": "non@molestie.edu",
		"phone": "1-350-584-6457",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "tortor.",
		"activeStatus": false,
		"lastContactDate": "2021-02-15T09:31:14-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Diam Proin Dolor Ltd",
		"nextContactDate": "2021-06-04T18:38:28-07:00",
		"title": "nibh."
	},
	{
		"name": "Wyatt Hahn",
		"contactFrequency": "Quarterly",
		"email": "non@volutpat.co.uk",
		"phone": "1-142-340-9259",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "dapibus",
		"activeStatus": true,
		"lastContactDate": "2021-06-23T04:00:53-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Libero Morbi Foundation",
		"nextContactDate": "2020-12-11T16:02:45-08:00",
		"title": "eleifend nec,"
	},
	{
		"name": "Zena Lowe",
		"contactFrequency": "Quarterly",
		"email": "Phasellus.at.augue@musProin.com",
		"phone": "1-832-950-9535",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "mollis",
		"activeStatus": false,
		"lastContactDate": "2021-04-08T13:28:56-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Malesuada Integer Consulting",
		"nextContactDate": "2020-09-26T14:45:27-07:00",
		"title": "egestas"
	},
	{
		"name": "Orli Frederick",
		"contactFrequency": "Monthly",
		"email": "odio.Nam.interdum@felisNullatempor.com",
		"phone": "1-398-468-2415",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "dui,",
		"activeStatus": false,
		"lastContactDate": "2020-09-19T03:19:38-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Vel Convallis LLP",
		"nextContactDate": "2021-01-10T20:37:02-08:00",
		"title": "malesuada augue"
	},
	{
		"name": "Herrod S. Barlow",
		"contactFrequency": "Biannual",
		"email": "aliquam.iaculis@nisimagnased.com",
		"phone": "1-627-787-3794",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "metus.",
		"activeStatus": true,
		"lastContactDate": "2021-04-21T17:55:56-07:00",
		"notes": "Lorem ipsum dolor sit",
		"company": "Velit Egestas Lacinia Limited",
		"nextContactDate": "2020-11-18T12:11:33-08:00",
		"title": "erat, eget tincidunt"
	},
	{
		"name": "Aquila Cooper",
		"contactFrequency": "None",
		"email": "magna.a.tortor@Pellentesqueultriciesdignissim.com",
		"phone": "1-202-550-0279",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "vestibulum",
		"activeStatus": true,
		"lastContactDate": "2021-01-02T07:38:48-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Nam Ligula Institute",
		"nextContactDate": "2020-08-19T07:34:54-07:00",
		"title": "nisi"
	},
	{
		"name": "Kelsey Dunlap",
		"contactFrequency": "Yearly",
		"email": "Aliquam.gravida.mauris@placerat.edu",
		"phone": "1-338-114-1848",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "id",
		"activeStatus": false,
		"lastContactDate": "2021-04-14T15:57:20-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Ligula Ltd",
		"nextContactDate": "2021-05-26T13:33:45-07:00",
		"title": "mattis ornare, lectus"
	},
	{
		"name": "Francis Noble",
		"contactFrequency": "Monthly",
		"email": "massa.Suspendisse@velitPellentesque.com",
		"phone": "1-929-518-0799",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "felis.",
		"activeStatus": false,
		"lastContactDate": "2020-09-01T08:22:42-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Vulputate Nisi Sem LLC",
		"nextContactDate": "2020-12-22T00:15:15-08:00",
		"title": "Nam nulla magna,"
	},
	{
		"name": "Clark M. Sparks",
		"contactFrequency": "Biannual",
		"email": "lorem.tristique@Donecnibh.org",
		"phone": "1-683-159-0094",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "nunc",
		"activeStatus": false,
		"lastContactDate": "2021-01-01T18:22:49-08:00",
		"notes": "Lorem ipsum dolor",
		"company": "Sem Pellentesque Institute",
		"nextContactDate": "2021-04-11T12:17:10-07:00",
		"title": "auctor, nunc"
	},
	{
		"name": "Hayfa Melendez",
		"contactFrequency": "Monthly",
		"email": "dolor@Inmipede.co.uk",
		"phone": "1-215-297-5715",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "sit",
		"activeStatus": true,
		"lastContactDate": "2021-02-20T06:47:52-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Blandit Limited",
		"nextContactDate": "2021-02-22T06:53:14-08:00",
		"title": "sed, facilisis vitae,"
	},
	{
		"name": "Fuller Roman",
		"contactFrequency": "None",
		"email": "condimentum@sagittis.edu",
		"phone": "1-496-795-1260",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "orci",
		"activeStatus": false,
		"lastContactDate": "2020-08-17T21:10:03-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Iaculis Company",
		"nextContactDate": "2021-07-01T18:15:43-07:00",
		"title": "ipsum. Phasellus"
	},
	{
		"name": "Maia B. Roberson",
		"contactFrequency": "Quarterly",
		"email": "Phasellus.nulla.Integer@sociis.com",
		"phone": "1-872-374-4570",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "at",
		"activeStatus": false,
		"lastContactDate": "2020-11-22T15:45:42-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Tempor Augue Ac Associates",
		"nextContactDate": "2021-05-12T00:42:35-07:00",
		"title": "dui lectus rutrum"
	},
	{
		"name": "Lysandra V. Craig",
		"contactFrequency": "Biannual",
		"email": "eleifend.non.dapibus@Vivamussitamet.org",
		"phone": "1-599-984-9417",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "vulputate",
		"activeStatus": true,
		"lastContactDate": "2020-08-05T18:52:21-07:00",
		"notes": "Lorem ipsum dolor sit amet,",
		"company": "Cras Corporation",
		"nextContactDate": "2021-06-17T21:01:53-07:00",
		"title": "Suspendisse"
	},
	{
		"name": "Rhonda Z. Allen",
		"contactFrequency": "None",
		"email": "eu@MorbivehiculaPellentesque.net",
		"phone": "1-977-433-9022",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "Vestibulum",
		"activeStatus": false,
		"lastContactDate": "2021-04-21T13:38:41-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Suspendisse Sed Ltd",
		"nextContactDate": "2021-07-10T08:14:20-07:00",
		"title": "sodales nisi magna"
	},
	{
		"name": "Andrew G. Reese",
		"contactFrequency": "Monthly",
		"email": "a@nonnisi.edu",
		"phone": "1-345-261-3326",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "molestie",
		"activeStatus": false,
		"lastContactDate": "2020-10-25T19:42:20-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Hendrerit Donec Porttitor Foundation",
		"nextContactDate": "2021-07-07T23:59:59-07:00",
		"title": "porttitor vulputate, posuere"
	},
	{
		"name": "Lana Ortiz",
		"contactFrequency": "Weekly",
		"email": "parturient.montes@ametconsectetueradipiscing.com",
		"phone": "1-431-981-9865",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "mi",
		"activeStatus": false,
		"lastContactDate": "2021-06-22T07:31:41-07:00",
		"notes": "Lorem",
		"company": "Aliquam Consulting",
		"nextContactDate": "2020-09-12T11:06:05-07:00",
		"title": "scelerisque dui. Suspendisse"
	},
	{
		"name": "Echo B. Conway",
		"contactFrequency": "BiWeekly",
		"email": "diam.eu.dolor@pedenonummyut.co.uk",
		"phone": "1-691-462-3665",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "amet",
		"activeStatus": false,
		"lastContactDate": "2021-02-03T18:42:16-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Ac Turpis Corp.",
		"nextContactDate": "2020-10-02T06:46:41-07:00",
		"title": "fermentum"
	},
	{
		"name": "Cairo G. Reynolds",
		"contactFrequency": "BiWeekly",
		"email": "nec.leo.Morbi@orciluctuset.co.uk",
		"phone": "1-825-858-7650",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "Curabitur",
		"activeStatus": true,
		"lastContactDate": "2020-12-21T18:38:41-08:00",
		"notes": "Lorem ipsum dolor sit",
		"company": "Sed Est Corp.",
		"nextContactDate": "2021-03-29T17:42:38-07:00",
		"title": "elementum sem, vitae"
	},
	{
		"name": "Nita Monroe",
		"contactFrequency": "None",
		"email": "Quisque.porttitor.eros@temporarcu.com",
		"phone": "1-605-140-1149",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "nec",
		"activeStatus": true,
		"lastContactDate": "2021-02-12T15:23:29-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Eros Non Enim Inc.",
		"nextContactDate": "2021-07-06T19:15:56-07:00",
		"title": "lectus. Cum"
	},
	{
		"name": "Laurel Massey",
		"contactFrequency": "Biannual",
		"email": "non.lacinia@Aeneaneuismodmauris.ca",
		"phone": "1-836-277-2914",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "euismod",
		"activeStatus": false,
		"lastContactDate": "2021-06-19T04:42:10-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Eget PC",
		"nextContactDate": "2021-05-14T14:16:39-07:00",
		"title": "vitae"
	},
	{
		"name": "Miriam Shaw",
		"contactFrequency": "Monthly",
		"email": "dui.nec.tempus@musAenean.ca",
		"phone": "1-359-963-3401",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "et",
		"activeStatus": false,
		"lastContactDate": "2020-08-27T16:48:36-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Nullam Feugiat Industries",
		"nextContactDate": "2021-06-06T04:55:21-07:00",
		"title": "Nunc mauris"
	},
	{
		"name": "Miriam A. Hobbs",
		"contactFrequency": "Monthly",
		"email": "vel.sapien.imperdiet@Maurisvelturpis.net",
		"phone": "1-905-929-3476",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "Ut",
		"activeStatus": true,
		"lastContactDate": "2021-05-06T16:13:56-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Ultrices Posuere Corporation",
		"nextContactDate": "2021-01-27T07:02:32-08:00",
		"title": "libero"
	},
	{
		"name": "Kessie Nguyen",
		"contactFrequency": "None",
		"email": "gravida.sagittis.Duis@pedesagittis.net",
		"phone": "1-953-164-0411",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "at",
		"activeStatus": true,
		"lastContactDate": "2021-03-11T00:05:55-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Vel Quam LLC",
		"nextContactDate": "2020-11-05T12:46:17-08:00",
		"title": "Sed diam"
	},
	{
		"name": "Jayme Slater",
		"contactFrequency": "Quarterly",
		"email": "varius.Nam.porttitor@vulputate.org",
		"phone": "1-528-238-1679",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "Sed",
		"activeStatus": true,
		"lastContactDate": "2021-05-31T19:39:36-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
		"company": "In Tincidunt Congue Company",
		"nextContactDate": "2021-03-10T11:24:38-08:00",
		"title": "magna. Phasellus dolor"
	},
	{
		"name": "Honorato K. Juarez",
		"contactFrequency": "Monthly",
		"email": "nunc.sit.amet@Morbineque.org",
		"phone": "1-219-121-8598",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "Suspendisse",
		"activeStatus": true,
		"lastContactDate": "2020-10-05T04:42:53-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Suscipit Incorporated",
		"nextContactDate": "2020-10-15T12:24:55-07:00",
		"title": "Etiam"
	},
	{
		"name": "Amal Roy",
		"contactFrequency": "Biannual",
		"email": "odio.Phasellus@in.com",
		"phone": "1-648-545-7815",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "familiar",
		"contextSpace": "luctus",
		"activeStatus": true,
		"lastContactDate": "2020-08-16T04:59:10-07:00",
		"notes": "Lorem ipsum dolor",
		"company": "Et Limited",
		"nextContactDate": "2020-11-13T10:01:21-08:00",
		"title": "id"
	},
	{
		"name": "Ferris T. Sosa",
		"contactFrequency": "Quarterly",
		"email": "cubilia.Curae.Donec@tortornibhsit.org",
		"phone": "1-380-233-5164",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "primis",
		"activeStatus": false,
		"lastContactDate": "2020-08-13T02:19:26-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Quis Urna Ltd",
		"nextContactDate": "2021-03-13T04:34:15-08:00",
		"title": "magna et ipsum"
	},
	{
		"name": "Tara Y. Patel",
		"contactFrequency": "None",
		"email": "lacinia.mattis.Integer@amet.co.uk",
		"phone": "1-458-891-0395",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "Fusce",
		"activeStatus": true,
		"lastContactDate": "2021-05-31T21:45:17-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Sem Molestie Associates",
		"nextContactDate": "2021-03-12T19:37:29-08:00",
		"title": "dolor dolor,"
	},
	{
		"name": "Byron Molina",
		"contactFrequency": "Quarterly",
		"email": "auctor.nunc.nulla@arcuVivamussit.org",
		"phone": "1-108-860-6693",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "placerat",
		"activeStatus": true,
		"lastContactDate": "2020-08-22T23:11:51-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Adipiscing Fringilla PC",
		"nextContactDate": "2021-01-06T07:00:43-08:00",
		"title": "fringilla. Donec"
	},
	{
		"name": "Brooke C. Aguirre",
		"contactFrequency": "None",
		"email": "egestas.hendrerit.neque@etultrices.co.uk",
		"phone": "1-456-894-8148",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "Nullam",
		"activeStatus": true,
		"lastContactDate": "2021-01-17T14:54:57-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Ornare Lectus Justo Ltd",
		"nextContactDate": "2021-03-03T06:40:24-08:00",
		"title": "urna,"
	},
	{
		"name": "Arthur H. Livingston",
		"contactFrequency": "Weekly",
		"email": "nisi.dictum@eleifend.co.uk",
		"phone": "1-260-928-6035",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "sed",
		"activeStatus": false,
		"lastContactDate": "2020-11-12T15:57:34-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",
		"company": "Natoque Penatibus Et Institute",
		"nextContactDate": "2020-11-14T00:11:20-08:00",
		"title": "erat vitae"
	},
	{
		"name": "Yolanda Marquez",
		"contactFrequency": "Monthly",
		"email": "ac@luctus.com",
		"phone": "1-640-758-7664",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "ut,",
		"activeStatus": true,
		"lastContactDate": "2021-06-08T16:11:56-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Massa Rutrum Corporation",
		"nextContactDate": "2021-03-21T21:36:45-07:00",
		"title": "ullamcorper. Duis"
	},
	{
		"name": "Jakeem D. Glover",
		"contactFrequency": "Quarterly",
		"email": "eu.odio.Phasellus@enim.ca",
		"phone": "1-879-141-6444",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "placerat.",
		"activeStatus": false,
		"lastContactDate": "2020-12-27T20:54:19-08:00",
		"notes": "Lorem ipsum dolor sit",
		"company": "Tempor Bibendum Associates",
		"nextContactDate": "2021-03-09T05:34:17-08:00",
		"title": "In scelerisque scelerisque"
	},
	{
		"name": "Melinda I. Wiley",
		"contactFrequency": "Biannual",
		"email": "interdum.Curabitur@ante.org",
		"phone": "1-268-390-9120",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "Fusce",
		"activeStatus": false,
		"lastContactDate": "2021-02-07T03:27:29-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Quisque Fringilla Euismod Corp.",
		"nextContactDate": "2020-08-14T11:19:03-07:00",
		"title": "habitant morbi"
	},
	{
		"name": "Dean J. Hays",
		"contactFrequency": "Yearly",
		"email": "diam.vel@Innec.co.uk",
		"phone": "1-782-842-9088",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "Nulla",
		"activeStatus": false,
		"lastContactDate": "2021-04-24T18:47:08-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Nulla Tincidunt Neque Company",
		"nextContactDate": "2021-06-22T19:38:25-07:00",
		"title": "fermentum convallis"
	},
	{
		"name": "Maryam Erickson",
		"contactFrequency": "Biannual",
		"email": "neque.sed@Cras.com",
		"phone": "1-421-390-1700",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "at",
		"activeStatus": false,
		"lastContactDate": "2020-12-31T05:29:48-08:00",
		"notes": "Lorem ipsum dolor sit",
		"company": "Donec Nibh LLP",
		"nextContactDate": "2021-03-18T02:50:28-07:00",
		"title": "rhoncus. Donec est."
	},
	{
		"name": "Otto Kennedy",
		"contactFrequency": "Monthly",
		"email": "laoreet.posuere@semmollis.net",
		"phone": "1-429-759-3300",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "sed",
		"activeStatus": false,
		"lastContactDate": "2021-07-24T08:30:23-07:00",
		"notes": "Lorem ipsum",
		"company": "Lacus Nulla Tincidunt Consulting",
		"nextContactDate": "2021-03-20T07:11:39-07:00",
		"title": "netus et malesuada"
	},
	{
		"name": "Britanni N. Baker",
		"contactFrequency": "Monthly",
		"email": "odio.auctor@neque.co.uk",
		"phone": "1-278-302-0517",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "Suspendisse",
		"activeStatus": true,
		"lastContactDate": "2021-01-23T05:23:26-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Neque Associates",
		"nextContactDate": "2020-12-07T16:30:10-08:00",
		"title": "Ut tincidunt"
	},
	{
		"name": "Sylvia Wiley",
		"contactFrequency": "Quarterly",
		"email": "Duis@iaculisodioNam.co.uk",
		"phone": "1-319-416-5241",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "felis",
		"activeStatus": false,
		"lastContactDate": "2020-08-01T21:23:50-07:00",
		"notes": "Lorem ipsum",
		"company": "Dictum Eleifend Nunc Foundation",
		"nextContactDate": "2021-07-18T19:18:19-07:00",
		"title": "sollicitudin commodo"
	},
	{
		"name": "Cain B. Sanford",
		"contactFrequency": "Quarterly",
		"email": "dictum.eu.eleifend@velitSedmalesuada.ca",
		"phone": "1-362-145-1945",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "porttitor",
		"activeStatus": true,
		"lastContactDate": "2021-04-03T23:08:13-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Amet LLC",
		"nextContactDate": "2021-02-22T08:46:55-08:00",
		"title": "urna. Nunc quis"
	},
	{
		"name": "Amela Gibbs",
		"contactFrequency": "Biannual",
		"email": "adipiscing.Mauris.molestie@vitae.edu",
		"phone": "1-606-499-2833",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "Nunc",
		"activeStatus": false,
		"lastContactDate": "2020-08-13T19:57:07-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Nunc Associates",
		"nextContactDate": "2021-01-20T10:12:04-08:00",
		"title": "faucibus lectus, a"
	},
	{
		"name": "Nehru V. Romero",
		"contactFrequency": "Monthly",
		"email": "dignissim.tempor.arcu@mauris.ca",
		"phone": "1-607-446-2372",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "Nullam",
		"activeStatus": false,
		"lastContactDate": "2021-03-09T18:30:26-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Sem LLC",
		"nextContactDate": "2021-05-30T07:16:03-07:00",
		"title": "morbi tristique"
	},
	{
		"name": "Holly M. Lindsey",
		"contactFrequency": "BiWeekly",
		"email": "Duis.sit.amet@vulputate.edu",
		"phone": "1-498-829-4774",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "nec,",
		"activeStatus": true,
		"lastContactDate": "2020-12-06T22:18:31-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "In Faucibus Morbi Inc.",
		"nextContactDate": "2021-06-14T20:26:53-07:00",
		"title": "aliquet"
	},
	{
		"name": "Lillith Y. Willis",
		"contactFrequency": "Biannual",
		"email": "erat@vel.co.uk",
		"phone": "1-946-215-3997",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "intimate",
		"contextSpace": "eget",
		"activeStatus": false,
		"lastContactDate": "2021-04-20T09:04:37-07:00",
		"notes": "Lorem",
		"company": "Nunc Mauris Corp.",
		"nextContactDate": "2021-01-11T22:25:32-08:00",
		"title": "magna. Cras"
	},
	{
		"name": "Ira Beasley",
		"contactFrequency": "Yearly",
		"email": "mollis.lectus@commodo.edu",
		"phone": "1-385-859-4575",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "interdum",
		"activeStatus": true,
		"lastContactDate": "2021-02-14T15:41:35-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Sed Leo Cras Foundation",
		"nextContactDate": "2021-06-06T04:41:06-07:00",
		"title": "vulputate mauris"
	},
	{
		"name": "Bert A. Fulton",
		"contactFrequency": "Biannual",
		"email": "Mauris.quis.turpis@idsapienCras.ca",
		"phone": "1-758-138-8829",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "Aenean",
		"activeStatus": true,
		"lastContactDate": "2021-04-25T13:24:52-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Et Nunc Corporation",
		"nextContactDate": "2021-03-17T06:16:11-07:00",
		"title": "id, erat."
	},
	{
		"name": "Lisandra Eaton",
		"contactFrequency": "Monthly",
		"email": "diam@mattis.ca",
		"phone": "1-805-374-0243",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "meaningful",
		"contextSpace": "montes,",
		"activeStatus": false,
		"lastContactDate": "2020-10-29T13:19:33-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Rhoncus Associates",
		"nextContactDate": "2021-02-27T10:40:50-08:00",
		"title": "dapibus gravida."
	},
	{
		"name": "Adena F. Workman",
		"contactFrequency": "Yearly",
		"email": "aptent@Donec.net",
		"phone": "1-587-564-6342",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "molestie.",
		"activeStatus": true,
		"lastContactDate": "2020-09-03T02:36:21-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Molestie Dapibus Limited",
		"nextContactDate": "2021-04-13T05:44:16-07:00",
		"title": "Cras eget"
	},
	{
		"name": "Hammett Moss",
		"contactFrequency": "None",
		"email": "nisi.a.odio@loremtristiquealiquet.com",
		"phone": "1-605-138-7993",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "vulputate,",
		"activeStatus": false,
		"lastContactDate": "2021-03-06T23:18:48-08:00",
		"notes": "Lorem",
		"company": "Mauris Corporation",
		"nextContactDate": "2020-09-26T20:17:21-07:00",
		"title": "scelerisque, lorem"
	},
	{
		"name": "Zahir S. Duke",
		"contactFrequency": "Biannual",
		"email": "vulputate.lacus.Cras@ipsumprimisin.org",
		"phone": "1-795-938-2362",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "unfamiliar",
		"contextSpace": "Quisque",
		"activeStatus": false,
		"lastContactDate": "2020-10-18T15:49:11-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
		"company": "Nullam Industries",
		"nextContactDate": "2020-12-24T14:38:44-08:00",
		"title": "arcu imperdiet"
	},
	{
		"name": "Quamar Oneil",
		"contactFrequency": "Monthly",
		"email": "Sed@elementum.org",
		"phone": "1-271-101-2558",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "a",
		"activeStatus": true,
		"lastContactDate": "2021-07-11T19:54:44-07:00",
		"notes": "Lorem ipsum dolor",
		"company": "Sagittis LLP",
		"nextContactDate": "2021-04-22T18:16:31-07:00",
		"title": "pretium"
	},
	{
		"name": "Chantale J. Pugh",
		"contactFrequency": "Biannual",
		"email": "conubia@eumetusIn.net",
		"phone": "1-389-349-4360",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "egestas",
		"activeStatus": false,
		"lastContactDate": "2020-12-02T10:16:53-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Per Institute",
		"nextContactDate": "2020-08-29T13:37:40-07:00",
		"title": "non"
	},
	{
		"name": "Chadwick Bowman",
		"contactFrequency": "Quarterly",
		"email": "arcu.imperdiet.ullamcorper@a.ca",
		"phone": "1-427-400-3451",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "dolor.",
		"activeStatus": true,
		"lastContactDate": "2021-03-20T07:54:48-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
		"company": "Vitae Orci PC",
		"nextContactDate": "2020-11-27T22:38:32-08:00",
		"title": "luctus,"
	},
	{
		"name": "Uriah F. Shepard",
		"contactFrequency": "BiWeekly",
		"email": "Duis@sitametfaucibus.com",
		"phone": "1-542-270-7303",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "sed",
		"activeStatus": false,
		"lastContactDate": "2020-12-04T13:33:00-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
		"company": "Purus In Company",
		"nextContactDate": "2020-12-26T03:17:57-08:00",
		"title": "eu metus."
	},
	{
		"name": "Abraham Caldwell",
		"contactFrequency": "Yearly",
		"email": "nec.enim@ligula.net",
		"phone": "1-432-978-5504",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "magnis",
		"activeStatus": false,
		"lastContactDate": "2021-07-22T03:41:49-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Orci Sem LLP",
		"nextContactDate": "2020-09-20T06:23:06-07:00",
		"title": "Duis"
	},
	{
		"name": "Macey Randolph",
		"contactFrequency": "Monthly",
		"email": "sit.amet@orciinconsequat.co.uk",
		"phone": "1-597-447-2987",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "nec,",
		"activeStatus": false,
		"lastContactDate": "2020-09-20T23:56:23-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna",
		"company": "Sed Dolor Fusce Inc.",
		"nextContactDate": "2021-03-06T10:21:52-08:00",
		"title": "Aliquam"
	},
	{
		"name": "Burton Z. Parks",
		"contactFrequency": "Yearly",
		"email": "eu.eros.Nam@vulputatemaurissagittis.edu",
		"phone": "1-107-484-3698",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "vitae",
		"activeStatus": true,
		"lastContactDate": "2021-06-30T16:37:23-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Cras Dolor Dolor Foundation",
		"nextContactDate": "2020-09-20T16:39:50-07:00",
		"title": "felis ullamcorper viverra."
	},
	{
		"name": "Scarlet K. Richards",
		"contactFrequency": "Yearly",
		"email": "est.ac@metus.com",
		"phone": "1-598-660-2204",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "Donec",
		"activeStatus": false,
		"lastContactDate": "2021-02-15T10:43:03-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Imperdiet Limited",
		"nextContactDate": "2020-11-08T04:27:57-08:00",
		"title": "nostra, per inceptos"
	},
	{
		"name": "Jorden E. Morrison",
		"contactFrequency": "Monthly",
		"email": "faucibus.ut.nulla@tinciduntvehicularisus.org",
		"phone": "1-528-976-3253",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "unfamiliar",
		"contextSpace": "velit.",
		"activeStatus": false,
		"lastContactDate": "2020-12-05T22:15:28-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.",
		"company": "Mauris Eu Institute",
		"nextContactDate": "2021-01-07T09:15:37-08:00",
		"title": "sem mollis dui,"
	},
	{
		"name": "Rudyard V. Henderson",
		"contactFrequency": "Yearly",
		"email": "leo.Vivamus.nibh@senectusetnetus.org",
		"phone": "1-676-317-3631",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "familiar",
		"contextSpace": "nisl",
		"activeStatus": false,
		"lastContactDate": "2021-03-04T17:29:50-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.",
		"company": "Erat Vel Pede LLC",
		"nextContactDate": "2020-08-02T03:34:55-07:00",
		"title": "velit. Pellentesque"
	},
	{
		"name": "Cassandra M. Castaneda",
		"contactFrequency": "BiWeekly",
		"email": "et@ac.co.uk",
		"phone": "1-878-128-0119",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "nunc",
		"activeStatus": true,
		"lastContactDate": "2021-03-24T20:41:27-07:00",
		"notes": "Lorem ipsum",
		"company": "Neque Nullam Nisl Corp.",
		"nextContactDate": "2021-06-14T20:33:07-07:00",
		"title": "velit."
	},
	{
		"name": "Dane Richardson",
		"contactFrequency": "Weekly",
		"email": "Phasellus.ornare@magnaPraesentinterdum.edu",
		"phone": "1-606-215-5359",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "intimate",
		"contextSpace": "dolor.",
		"activeStatus": false,
		"lastContactDate": "2021-01-29T18:24:56-08:00",
		"notes": "Lorem",
		"company": "Vitae Aliquam Associates",
		"nextContactDate": "2020-09-08T12:35:37-07:00",
		"title": "amet, risus. Donec"
	},
	{
		"name": "Chava V. Lott",
		"contactFrequency": "BiWeekly",
		"email": "libero.Proin@nec.ca",
		"phone": "1-712-453-0112",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "nisi",
		"activeStatus": false,
		"lastContactDate": "2021-03-06T15:01:57-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer",
		"company": "Dignissim Pharetra Industries",
		"nextContactDate": "2021-05-16T10:59:10-07:00",
		"title": "ornare egestas"
	},
	{
		"name": "Hannah Owens",
		"contactFrequency": "Yearly",
		"email": "velit@volutpat.co.uk",
		"phone": "1-295-328-4750",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "Integer",
		"activeStatus": false,
		"lastContactDate": "2020-11-10T13:57:01-08:00",
		"notes": "Lorem",
		"company": "Fringilla Foundation",
		"nextContactDate": "2020-12-05T15:56:37-08:00",
		"title": "neque"
	},
	{
		"name": "Mariko O. Beasley",
		"contactFrequency": "Yearly",
		"email": "mi@arcuVivamus.edu",
		"phone": "1-957-977-1786",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "Nunc",
		"activeStatus": true,
		"lastContactDate": "2021-05-28T13:33:53-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
		"company": "Nunc Ullamcorper Eu Industries",
		"nextContactDate": "2021-01-23T12:57:57-08:00",
		"title": "ac, eleifend"
	},
	{
		"name": "Jacob J. Heath",
		"contactFrequency": "Monthly",
		"email": "et.magnis@sit.ca",
		"phone": "1-489-587-8500",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "amet",
		"activeStatus": false,
		"lastContactDate": "2020-10-26T14:08:10-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Dolor Incorporated",
		"nextContactDate": "2020-08-22T09:54:37-07:00",
		"title": "Etiam bibendum fermentum"
	},
	{
		"name": "Oleg Bass",
		"contactFrequency": "Biannual",
		"email": "mi.ac.mattis@loremtristiquealiquet.ca",
		"phone": "1-434-648-8041",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "quam.",
		"activeStatus": false,
		"lastContactDate": "2021-07-13T11:29:21-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Egestas Ltd",
		"nextContactDate": "2021-03-06T16:58:02-08:00",
		"title": "tellus"
	},
	{
		"name": "Leilani Young",
		"contactFrequency": "Yearly",
		"email": "at.libero@lacus.ca",
		"phone": "1-561-296-7741",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "intimate",
		"contextSpace": "Nullam",
		"activeStatus": false,
		"lastContactDate": "2021-05-16T00:00:39-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
		"company": "Pede Nonummy Ut Company",
		"nextContactDate": "2020-08-29T02:00:39-07:00",
		"title": "Duis elementum,"
	},
	{
		"name": "Jennifer L. Barnett",
		"contactFrequency": "Quarterly",
		"email": "In.condimentum@Nuncquis.ca",
		"phone": "1-916-984-9122",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "low",
		"familiarity": "meaningful",
		"contextSpace": "est.",
		"activeStatus": false,
		"lastContactDate": "2021-03-13T09:40:14-08:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer",
		"company": "Nam Nulla Magna Corp.",
		"nextContactDate": "2020-10-18T01:06:14-07:00",
		"title": "eu arcu. Morbi"
	},
	{
		"name": "Cedric Riddle",
		"contactFrequency": "Monthly",
		"email": "auctor@sapienAenean.net",
		"phone": "1-733-789-9405",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "unfamiliar",
		"contextSpace": "a,",
		"activeStatus": true,
		"lastContactDate": "2020-08-16T18:46:22-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
		"company": "Malesuada Vel LLC",
		"nextContactDate": "2020-09-21T17:08:50-07:00",
		"title": "congue a,"
	},
	{
		"name": "Mason J. Todd",
		"contactFrequency": "Yearly",
		"email": "tempus.eu@atrisus.com",
		"phone": "1-505-178-2263",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "high",
		"familiarity": "meaningful",
		"contextSpace": "metus",
		"activeStatus": false,
		"lastContactDate": "2021-07-26T20:46:48-07:00",
		"notes": "Lorem ipsum dolor sit amet, consectetuer adipiscing",
		"company": "Cursus Limited",
		"nextContactDate": "2020-10-16T15:34:56-07:00",
		"title": "eros. Nam consequat"
	},
	{
		"name": "Clio Powers",
		"contactFrequency": "Quarterly",
		"email": "Aliquam.erat@dolor.com",
		"phone": "1-897-690-1806",
		"LinkedIn": "https://www.linkedin.com/",
		"priority": "medium",
		"familiarity": "familiar",
		"contextSpace": "elementum,",
		"activeStatus": true,
		"lastContactDate": "2021-03-30T09:08:11-07:00",
		"notes": "Lorem ipsum dolor",
		"company": "Phasellus Fermentum Convallis LLC",
		"nextContactDate": "2020-09-22T12:40:32-07:00",
		"title": "ornare,"
	}
]